In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
L1 = pd.read_csv("Web scrapping csv")
L1

Unnamed: 0                                             Laptop  Rating  \
0             0  Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6   
1             1  MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0   
2             2  Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0   
3             3  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5   
4             4  MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5   
5             5  Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0   
6             6  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3   
7             7  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0   
8             8  Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5   
9             9  MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9   
10           10  Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5   
11           11  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3   
12           12  MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5   
13           13  Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4   
14           14  Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6   
15           15  MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5   
16           16  Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5   
17           17  Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7   
18           18  MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN   
19           19  Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5   
20           20  HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1   
21           21  Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6   
22           22  Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3   
23           23  MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6   
24           24  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1   
25           25  HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3   
26           26  Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1   
27           27  Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1   
28           28  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
29           29  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1   
..          ...                                                ...     ...   
784         784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0   
785         785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9   
786         786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5   
787         787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4   
788         788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4   
789         789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2   
790         790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8   
791         791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9   
792         792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5   
793         793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2   
794         794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3   
795         795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN   
796         796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8   
797         797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0   
798         798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7   
799         799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0   
800         800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN   
801         801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7   
802         802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0   
803         803  Dell G3 Se

In [4]:
L1.shape

(814, 11)

## Data cleaning and understanding the data

> - There are 814 rows and 11 columns in my dataset.

In [5]:
print(L1['Brands'])

0                              Acer Predator Helios 300 
1                                                MSI GS 
2                                            Asus FX503 
3                                              Asus TUF 
4                                                MSI GE 
5                                Asus ROG Strix Edition 
6                                              Asus ROG 
7                                              Asus ROG 
8                              Acer Predator Helios 300 
9                                         MSI GL Series 
10                                         Acer Nitro 5 
11                                             Asus TUF 
12                                        MSI GV Series 
13                                           Asus FX553 
14                                        Lenovo Legion 
15                                               MSI GL 
16                               Asus ROG Strix Edition 
17                             

In [6]:
L1['Processor']

0        i5 8th Gen
1        i7 8th Gen
2        i7 7th Gen
3        i5 8th Gen
4        i7 8th Gen
5        i7 7th Gen
6        i7 7th Gen
7        i7 7th Gen
8        i5 7th Gen
9        i7 7th Gen
10       i5 7th Gen
11       i5 8th Gen
12       i7 8th Gen
13       i7 7th Gen
14       i5 7th Gen
15       i7 8th Gen
16       i7 8th Gen
17       i5 5th Gen
18       i7 9th Gen
19       i5 8th Gen
20     Dual Core A9
21       i5 8th Gen
22       i3 7th Gen
23       i5 9th Gen
24       i3 7th Gen
25       i5 8th Gen
26      3 Dual Core
27       i5 8th Gen
28       i5 8th Gen
29       i3 7th Gen
           ...     
784      i5 8th Gen
785      i5 8th Gen
786      i5 7th Gen
787      i5 7th Gen
788             NaN
789      i5 8th Gen
790      i7 9th Gen
791     i5 10th Gen
792      i5 8th Gen
793      i3 7th Gen
794             NaN
795      i7 9th Gen
796      i5 8th Gen
797             NaN
798      i5 8th Gen
799      i3 7th Gen
800      i3 7th Gen
801      i7 8th Gen
802      i3 7th Gen


In [7]:
B=[]
C =[]
for i in L1['Brands']:
    d = list(i.split())
    B.append(d[0])
    a = ' '.join(d[1:])
    #if a:
    C.append(a)
    #print(a)
    #else:
     #   C.append(np.nan)
print(B)
print(C)


['Acer', 'MSI', 'Asus', 'Asus', 'MSI', 'Asus', 'Asus', 'Asus', 'Acer', 'MSI', 'Acer', 'Asus', 'MSI', 'Asus', 'Lenovo', 'MSI', 'Asus', 'Apple', 'MSI', 'Acer', 'HP', 'Acer', 'Asus', 'MSI', 'Lenovo', 'HP', 'Acer', 'Dell', 'Dell', 'Dell', 'Lenovo', 'Dell', 'Acer', 'Acer', 'Lenovo', 'Acer', 'Asus', 'Lenovo', 'MSI', 'MSI', 'Avita', 'Dell', 'HP', 'HP', 'Acer', 'Asus', 'HP', 'Dell', 'Lenovo', 'Acer', 'Asus', 'Acer', 'Dell', 'Asus', 'Avita', 'Asus', 'HP', 'Lenovo', 'Asus', 'Lenovo', 'Asus', 'Asus', 'Asus', 'Avita', 'Asus', 'Asus', 'HP', 'Acer', 'HP', 'HP', 'Asus', 'Lenovo', 'Asus', 'Lenovo', 'Asus', 'MSI', 'HP', 'Dell', 'Acer', 'HP', 'Asus', 'Asus', 'Lenovo', 'HP', 'HP', 'Asus', 'Dell', 'HP', 'MSI', 'Acer', 'HP', 'Asus', 'Acer', 'HP', 'Lenovo', 'MSI', 'Asus', 'Avita', 'Asus', 'HP', 'HP', 'HP', 'HP', 'HP', 'Asus', 'Avita', 'Asus', 'HP', 'Avita', 'HP', 'Dell', 'Lenovo', 'Asus', 'Acer', 'Apple', 'Dell', 'MSI', 'HP', 'HP', 'Asus', 'Nexstgo', 'Acer', 'Asus', 'Dell', 'Dell', 'Acer', 'Alienware', 'Del

In [8]:
type('Brands')

str

In [9]:
len(B)

814

In [10]:
len(C)

814

In [11]:
L1['Brands']=B

In [12]:
L1

Unnamed: 0                                             Laptop  Rating  \
0             0  Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6   
1             1  MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0   
2             2  Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0   
3             3  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5   
4             4  MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5   
5             5  Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0   
6             6  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3   
7             7  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0   
8             8  Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5   
9             9  MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9   
10           10  Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5   
11           11  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3   
12           12  MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5   
13           13  Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4   
14           14  Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6   
15           15  MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5   
16           16  Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5   
17           17  Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7   
18           18  MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN   
19           19  Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5   
20           20  HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1   
21           21  Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6   
22           22  Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3   
23           23  MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6   
24           24  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1   
25           25  HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3   
26           26  Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1   
27           27  Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1   
28           28  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
29           29  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1   
..          ...                                                ...     ...   
784         784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0   
785         785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9   
786         786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5   
787         787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4   
788         788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4   
789         789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2   
790         790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8   
791         791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9   
792         792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5   
793         793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2   
794         794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3   
795         795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN   
796         796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8   
797         797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0   
798         798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7   
799         799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0   
800         800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN   
801         801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7   
802         802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0   
803         803  Dell G3 Se

In [13]:

#if C:
 #   Model.append(C)
#else:
 #   Model.append(np.nan)

In [14]:
L1['Model']=C

In [15]:
L1

Unnamed: 0                                             Laptop  Rating  \
0             0  Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6   
1             1  MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0   
2             2  Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0   
3             3  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5   
4             4  MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5   
5             5  Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0   
6             6  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3   
7             7  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0   
8             8  Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5   
9             9  MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9   
10           10  Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5   
11           11  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3   
12           12  MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5   
13           13  Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4   
14           14  Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6   
15           15  MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5   
16           16  Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5   
17           17  Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7   
18           18  MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN   
19           19  Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5   
20           20  HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1   
21           21  Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6   
22           22  Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3   
23           23  MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6   
24           24  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1   
25           25  HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3   
26           26  Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1   
27           27  Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1   
28           28  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
29           29  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1   
..          ...                                                ...     ...   
784         784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0   
785         785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9   
786         786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5   
787         787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4   
788         788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4   
789         789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2   
790         790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8   
791         791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9   
792         792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5   
793         793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2   
794         794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3   
795         795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN   
796         796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8   
797         797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0   
798         798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7   
799         799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0   
800         800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN   
801         801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7   
802         802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0   
803         803  Dell G3 Se

In [16]:
#L1.drop(801,inplace=True)

In [17]:
L1.drop(columns='Unnamed: 0',inplace=True)

- I have dropped the unncessary column named Unnamed: 0 from my data for having better understanding.

In [18]:
L1

Laptop  Rating  Disc_price  \
0    Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6       55990   
1    MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0      149990   
2    Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0       87990   
3    Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5       66990   
4    MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5      179990   
5    Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0       92990   
6    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3      107990   
7    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0      146490   
8    Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5      129999   
9    MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9       83990   
10   Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5       52990   
11   Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3       72990   
12   MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5       94990   
13   Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4       68990   
14   Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6       61990   
15   MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5       72990   
16   Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5       90990   
17   Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7       54990   
18   MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN      189990   
19   Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5       41990   
20   HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1       19990   
21   Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6       44990   
22   Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3       28990   
23   MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6       54990   
24   Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1       25990   
25   HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3       49990   
26   Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1       21990   
27   Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1       38990   
28   Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
29   Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1       23990   
..                                                 ...     ...         ...   
784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0       52500   
785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9       71890   
786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5       79999   
787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4       81990   
788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4       29999   
789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2       78990   
790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8      144990   
791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9       67999   
792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5       58244   
793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2       27990   
794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3         299   
795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN       84990   
796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8      164990   
797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0       36990   
798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7       96499   
799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0       24990   
800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN       27690   
801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7       84990   
802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0       27990   
803  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       5

In [19]:
#L1.reset_index(inplace=True)

In [20]:
L1.rename(columns={"OS":"Operating system"},inplace=True)

- I have renamed my OS column to operating system

In [21]:
L1

Laptop  Rating  Disc_price  \
0    Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6       55990   
1    MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0      149990   
2    Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0       87990   
3    Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5       66990   
4    MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5      179990   
5    Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0       92990   
6    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3      107990   
7    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0      146490   
8    Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5      129999   
9    MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9       83990   
10   Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5       52990   
11   Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3       72990   
12   MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5       94990   
13   Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4       68990   
14   Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6       61990   
15   MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5       72990   
16   Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5       90990   
17   Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7       54990   
18   MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN      189990   
19   Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5       41990   
20   HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1       19990   
21   Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6       44990   
22   Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3       28990   
23   MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6       54990   
24   Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1       25990   
25   HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3       49990   
26   Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1       21990   
27   Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1       38990   
28   Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
29   Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1       23990   
..                                                 ...     ...         ...   
784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0       52500   
785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9       71890   
786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5       79999   
787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4       81990   
788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4       29999   
789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2       78990   
790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8      144990   
791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9       67999   
792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5       58244   
793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2       27990   
794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3         299   
795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN       84990   
796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8      164990   
797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0       36990   
798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7       96499   
799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0       24990   
800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN       27690   
801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7       84990   
802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0       27990   
803  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       5

In [22]:
#L1.drop(columns='index',inplace=True)

In [23]:
type('Rating')
type('Disc_price')

str

str

In [24]:
type(L1['Disc_price'])

pandas.core.series.Series

In [25]:
for i in L1['No of Ratings']:
    type(i)

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

float

In [26]:
L1['Disc_price'].mean()

57935.174447174446

In [27]:
L1['Rating'].mean()

4.208180535966148

In [28]:
L1['Disc_price'].sum()

47159232

In [29]:
print(L1['No of Ratings'])
type(L1['No of Ratings'])

0      11530.0
1          9.0
2          2.0
3       1181.0
4         13.0
5          5.0
6         29.0
7          2.0
8       3199.0
9         27.0
10       405.0
11        56.0
12       746.0
13       351.0
14       359.0
15       712.0
16       108.0
17     20868.0
18         NaN
19      3682.0
20      6948.0
21      2341.0
22      2830.0
23       476.0
24      3594.0
25      1679.0
26       753.0
27       189.0
28       260.0
29      2359.0
        ...   
784        1.0
785        8.0
786      225.0
787       19.0
788      911.0
789       13.0
790        4.0
791       10.0
792       23.0
793     9365.0
794    25279.0
795        NaN
796       39.0
797        6.0
798      381.0
799     1730.0
800        NaN
801      154.0
802      218.0
803      260.0
804      245.0
805        NaN
806        NaN
807    14498.0
808        4.0
809     1679.0
810      114.0
811        NaN
812       57.0
813      357.0
Name: No of Ratings, Length: 814, dtype: float64


pandas.core.series.Series

In [30]:
L1['No of Ratings']

0      11530.0
1          9.0
2          2.0
3       1181.0
4         13.0
5          5.0
6         29.0
7          2.0
8       3199.0
9         27.0
10       405.0
11        56.0
12       746.0
13       351.0
14       359.0
15       712.0
16       108.0
17     20868.0
18         NaN
19      3682.0
20      6948.0
21      2341.0
22      2830.0
23       476.0
24      3594.0
25      1679.0
26       753.0
27       189.0
28       260.0
29      2359.0
        ...   
784        1.0
785        8.0
786      225.0
787       19.0
788      911.0
789       13.0
790        4.0
791       10.0
792       23.0
793     9365.0
794    25279.0
795        NaN
796       39.0
797        6.0
798      381.0
799     1730.0
800        NaN
801      154.0
802      218.0
803      260.0
804      245.0
805        NaN
806        NaN
807    14498.0
808        4.0
809     1679.0
810      114.0
811        NaN
812       57.0
813      357.0
Name: No of Ratings, Length: 814, dtype: float64

In [31]:
L1.shape

(814, 11)

In [32]:
L1['No of Ratings'].sum()

981554.0

In [33]:
L1['No of Reviews'].sum()

142984.0

In [34]:
L1.describe()

Rating     Disc_price  No of Ratings  No of Reviews     Ram[GB]
count  709.000000     814.000000     709.000000     709.000000  812.000000
mean     4.208181   57935.174447    1384.420310     201.669958    7.045567
std      0.388050   45492.042654    2778.156358     399.591873    4.192841
min      1.000000     299.000000       1.000000       0.000000    2.000000
25%      4.000000   28990.000000      31.000000       6.000000    4.000000
50%      4.200000   45990.000000     196.000000      31.000000    8.000000
75%      4.400000   68867.250000    1576.000000     227.000000    8.000000
max      5.000000  399990.000000   25279.000000    3848.000000   32.000000

In [35]:
L1

Laptop  Rating  Disc_price  \
0    Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6       55990   
1    MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0      149990   
2    Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0       87990   
3    Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5       66990   
4    MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5      179990   
5    Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0       92990   
6    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3      107990   
7    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0      146490   
8    Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5      129999   
9    MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9       83990   
10   Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5       52990   
11   Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3       72990   
12   MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5       94990   
13   Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4       68990   
14   Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6       61990   
15   MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5       72990   
16   Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5       90990   
17   Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7       54990   
18   MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN      189990   
19   Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5       41990   
20   HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1       19990   
21   Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6       44990   
22   Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3       28990   
23   MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6       54990   
24   Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1       25990   
25   HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3       49990   
26   Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1       21990   
27   Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1       38990   
28   Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
29   Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1       23990   
..                                                 ...     ...         ...   
784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0       52500   
785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9       71890   
786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5       79999   
787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4       81990   
788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4       29999   
789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2       78990   
790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8      144990   
791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9       67999   
792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5       58244   
793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2       27990   
794   Flipkart SmartBuy KM-206W Wireless Optical Mouse     4.3         299   
795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN       84990   
796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8      164990   
797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0       36990   
798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7       96499   
799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0       24990   
800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN       27690   
801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7       84990   
802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0       27990   
803  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       5

In [36]:
L1['Laptop'].loc[780:840]

780    MSI Core i9 9th Gen - (32 GB/1 TB HDD/1 TB SSD...
781    Lenovo Yoga 730 Core i5 8th Gen - (8 GB/512 GB...
782    Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...
783    HP Omen Core i5 7th Gen - (8 GB/1 TB HDD/128 G...
784    Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...
785    Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...
786    Microsoft Surface Pro Core i5 7th Gen - (4 GB/...
787    Microsoft Surface Core i5 7th Gen - (8 GB/128 ...
788    Microsoft Surface Go Pentium Gold - (4 GB/64 G...
789    Microsoft Surface Laptop 2 Core i5 8th Gen - (...
790    MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...
791    HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...
792    Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...
793    HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...
794     Flipkart SmartBuy KM-206W Wireless Optical Mouse
795    Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...
796    Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...
797    Asus VivoBook 15 Ryzen 5

In [37]:
L1.drop(807,inplace=True)

In [38]:
L1['Rating'].sum()

2979.1

In [39]:
L1['Ram[GB]'].sum()

5721.0

In [40]:
L1['Processor'].isnull().any()

True

In [41]:
L1['Processor'].value_counts()

i5 8th Gen              171
i3 7th Gen              140
i7 8th Gen               50
i5 7th Gen               43
i7 7th Gen               41
i3 6th Gen               40
i3 5th Gen               31
i7 9th Gen               31
i5 6th Gen               18
i3 4th Gen               17
i5 5th Gen               15
i5 9th Gen               14
i3 8th Gen               13
i7 6th Gen               12
Dual Core Processor4      8
Dual Core Processor2      8
i7 5th Gen                7
i5 10th Gen               6
Dual Core A9              6
i7 4th Gen                6
Dual Core E2              5
i5 4th Gen                5
i7 10th Gen               4
Dual Core 4th             4
Dual Core 5th             3
i9 9th Gen                2
Dual Core E1              2
Dual Core A4              2
Dual Core A6              2
i7 Processor4 GB          2
Dual Core 7th             1
i5 3rd Gen                1
3 Dual Core               1
i7 Processor16 GB         1
i3 10th Gen               1
i5 Processor4 GB    

In [42]:
L1['Processor'].value_counts().sum()

715

In [43]:
814-715

99

In [44]:
L1.loc[801:814]

Laptop  Rating  Disc_price  \
801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7       84990   
802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0       27990   
803  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
804  Asus X507UF Core i5 8th Gen - (8 GB/1 TB HDD/W...     4.4       41890   
805  Dell Inspiron 3000 Ryzen 3 Quad Core - (4 GB/1...     NaN       35247   
806  Asus ZenBook 14 Ryzen 5 Quad Core 3rd Gen - (8...     NaN       61990   
808  Asus Core i7 8th Gen - (8 GB/1 TB HDD/256 GB S...     4.0       56890   
809  HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3       49990   
810  Avita Liber Core i5 7th Gen - (8 GB/256 GB SSD...     4.4       42990   
811  MSI Core i7 9th Gen - (16 GB/1 TB SSD/Windows ...     NaN      214990   
812  Lenovo Core i5 7th Gen - (8 GB/1 TB HDD/Window...     4.1       64715   
813  Lenovo IdeaPad Pentium Quad Core - (4 GB/1 TB ...     4.0       23987   

     No of Ratings  No of Reviews   Processor  Ram[GB]              Storage  \
801          154.0           28.0  i7 8th Gen      8.0  1 TB HDD 256 GB SSD   
802          218.0           23.0  i3 7th Gen      4.0             1 TB HDD   
803          260.0           30.0  i5 8th Gen      8.0  1 TB HDD 128 GB SSD   
804          245.0           34.0  i5 8th Gen      8.0             1 TB HDD   
805            NaN            NaN         NaN      4.0             1 TB HDD   
806            NaN            NaN         NaN      8.0           512 GB SSD   
808            4.0            3.0  i7 8th Gen      8.0  1 TB HDD 256 GB SSD   
809         1679.0          227.0  i5 8th Gen      8.0             1 TB HDD   
810          114.0           30.0  i5 7th Gen      8.0           256 GB SSD   
811            NaN            NaN  i7 9th Gen     16.0             1 TB SSD   
812           57.0           21.0  i5 7th Gen      8.0             1 TB HDD   
813          357.0           57.0         NaN      4.0             1 TB HDD   

     Brands Operating system                       Model  
801    Asus  Windows 10 Home                VivoBook S14  
802  Lenovo  Windows 10 Home                 Ideapad 130  
803    Dell  Windows 10 Home                   G3 Series  
804    Asus       Windows 10                      X507UF  
805    Dell  Windows 10 Home  Inspiron 3000 Ryzen 3 Quad  
806    Asus  Windows 10 Home     ZenBook 14 Ryzen 5 Quad  
808    Asus  Windows 10 Home                              
809      HP  Windows 10 Home                 Pavilion 15  
810   Avita  Windows 10 Home                       Liber  
811     MSI  Windows 10 Home                              
812  Lenovo  Windows 10 Home                              
813  Lenovo              DOS        IdeaPad Pentium Quad

In [45]:
L1.drop(794,inplace=True)

- Firstly i have taken a brief description about the statistics for the numerical data by using describe() method
- I have dropped some unnecessary data which cannot be used in my analysis like some extra products we get for using laptops like mouse and adapter
- I found the no of laptops in particular brands used in my analysis
- Now we have readjusted and cleaned the data.
- After cleaning we have 812 rows and 11 columns.

In [46]:
L1.reset_index(inplace=True)
L1

index                                             Laptop  Rating  \
0        0  Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6   
1        1  MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0   
2        2  Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0   
3        3  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5   
4        4  MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5   
5        5  Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0   
6        6  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3   
7        7  Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0   
8        8  Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5   
9        9  MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9   
10      10  Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5   
11      11  Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3   
12      12  MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5   
13      13  Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4   
14      14  Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6   
15      15  MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5   
16      16  Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5   
17      17  Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7   
18      18  MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN   
19      19  Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5   
20      20  HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1   
21      21  Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6   
22      22  Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3   
23      23  MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6   
24      24  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1   
25      25  HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3   
26      26  Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1   
27      27  Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1   
28      28  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
29      29  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1   
..     ...                                                ...     ...   
782    782  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
783    783  HP Omen Core i5 7th Gen - (8 GB/1 TB HDD/128 G...     NaN   
784    784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0   
785    785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9   
786    786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5   
787    787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4   
788    788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4   
789    789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2   
790    790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8   
791    791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9   
792    792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5   
793    793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2   
794    795  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN   
795    796  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8   
796    797  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0   
797    798  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7   
798    799  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0   
799    800  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN   
800    801  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7   
801    802  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0   
802    803  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4   
803    804  Asus X507UF Core i5 8th Gen - (8 GB/1 TB HDD/W...     4.4   
804    805  Dell Inspiron 3000 Ryzen 3 Quad Core - (4 GB/1...  

In [47]:
L1.drop(columns={'index'},inplace=True)
L1

Laptop  Rating  Disc_price  \
0    Acer Predator Helios 300 Core i5 8th Gen - (8 ...     4.6       55990   
1    MSI GS Core i7 8th Gen - (16 GB/512 GB SSD/Win...     4.0      149990   
2    Asus FX503 Core i7 7th Gen - (8 GB/1 TB HDD/12...     5.0       87990   
3    Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.5       66990   
4    MSI GE Core i7 8th Gen - (16 GB/1 TB HDD/512 G...     4.5      179990   
5    Asus ROG Strix Edition Core i7 7th Gen - (8 GB...     4.0       92990   
6    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/Wind...     4.3      107990   
7    Asus ROG Core i7 7th Gen - (8 GB/1 TB HDD/256 ...     3.0      146490   
8    Acer Predator Helios 300 Core i5 7th Gen - (8 ...     4.5      129999   
9    MSI GL Series Core i7 7th Gen - (8 GB/1 TB HDD...     4.9       83990   
10   Acer Nitro 5 Core i5 7th Gen - (8 GB/1 TB HDD/...     4.5       52990   
11   Asus TUF Core i5 8th Gen - (8 GB/1 TB HDD/128 ...     4.3       72990   
12   MSI GV Series Core i7 8th Gen - (16 GB/1 TB HD...     4.5       94990   
13   Asus FX553 Core i7 7th Gen - (8 GB/1 TB HDD/Wi...     4.4       68990   
14   Lenovo Legion Core i5 7th Gen - (8 GB/1 TB HDD...     4.6       61990   
15   MSI GL Core i7 8th Gen - (8 GB/1 TB HDD/128 GB...     4.5       72990   
16   Asus ROG Strix Edition Core i7 8th Gen - (16 G...     4.5       90990   
17   Apple MacBook Air Core i5 5th Gen - (8 GB/128 ...     4.7       54990   
18   MSI Core i7 9th Gen - (16 GB/1 TB HDD/512 GB S...     NaN      189990   
19   Acer Aspire 5s Core i5 8th Gen - (8 GB/512 GB ...     4.5       41990   
20   HP 15q APU Dual Core A9 - (4 GB/1 TB HDD/Windo...     4.1       19990   
21   Acer Swift 3 Core i5 8th Gen - (8 GB/512 GB SS...     4.6       44990   
22   Asus VivoBook 14 Core i3 7th Gen - (4 GB/256 G...     4.3       28990   
23   MSI Core i5 9th Gen - (8 GB/512 GB SSD/Windows...     4.6       54990   
24   Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.1       25990   
25   HP Pavilion 15 Core i5 8th Gen - (8 GB/1 TB HD...     4.3       49990   
26   Acer Aspire 3 Ryzen 3 Dual Core - (4 GB/1 TB H...     4.1       21990   
27   Dell Vostro 3000 Core i5 8th Gen - (8 GB/1 TB ...     4.1       38990   
28   Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
29   Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.1       23990   
..                                                 ...     ...         ...   
782  Dell G3 Series Core i5 8th Gen - (8 GB/1 TB HD...     4.4       54990   
783  HP Omen Core i5 7th Gen - (8 GB/1 TB HDD/128 G...     NaN      137098   
784  Acer Spin Core i5 8th Gen - (8 GB/256 GB SSD/W...     4.0       52500   
785  Microsoft Surface Pro 6 Core i5 8th Gen - (8 G...     4.9       71890   
786  Microsoft Surface Pro Core i5 7th Gen - (4 GB/...     4.5       79999   
787  Microsoft Surface Core i5 7th Gen - (8 GB/128 ...     4.4       81990   
788  Microsoft Surface Go Pentium Gold - (4 GB/64 G...     4.4       29999   
789  Microsoft Surface Laptop 2 Core i5 8th Gen - (...     4.2       78990   
790  MSI Core i7 9th Gen - (16 GB/1 TB HDD/256 GB S...     4.8      144990   
791  HP Pavilion x360 Core i5 10th Gen - (8 GB/256 ...     4.9       67999   
792  Lenovo Ideapad 330 Core i5 8th Gen - (8 GB/1 T...     4.5       58244   
793  HP 14q Core i3 7th Gen - (4 GB/1 TB HDD/Window...     4.2       27990   
794  Acer NITRO 5 Core i7 9th Gen - (8 GB/1 TB HDD/...     NaN       84990   
795  Apple MacBook Pro Core i5 8th Gen - (8 GB/512 ...     4.8      164990   
796  Asus VivoBook 15 Ryzen 5 Quad Core - (4 GB/256...     5.0       36990   
797  Apple MacBook Air Core i5 8th Gen - (8 GB/128 ...     4.7       96499   
798  Dell 14 3000 Core i3 7th Gen - (4 GB/1 TB HDD/...     4.0       24990   
799  Asus VivoBook Core i3 7th Gen - (4 GB/1 TB HDD...     NaN       27690   
800  Asus VivoBook S14 Core i7 8th Gen - (8 GB/1 TB...     4.7       84990   
801  Lenovo Ideapad 130 Core i3 7th Gen - (4 GB/1 T...     4.0       2

In [48]:
L1.drop(columns='Laptop',inplace=True)
L1

Rating  Disc_price  No of Ratings  No of Reviews     Processor  Ram[GB]  \
0       4.6       55990        11530.0         1566.0    i5 8th Gen      8.0   
1       4.0      149990            9.0            2.0    i7 8th Gen     16.0   
2       5.0       87990            2.0            1.0    i7 7th Gen      8.0   
3       4.5       66990         1181.0          219.0    i5 8th Gen      8.0   
4       4.5      179990           13.0            3.0    i7 8th Gen     16.0   
5       4.0       92990            5.0            2.0    i7 7th Gen      8.0   
6       4.3      107990           29.0           11.0    i7 7th Gen      8.0   
7       3.0      146490            2.0            1.0    i7 7th Gen      8.0   
8       4.5      129999         3199.0          697.0    i5 7th Gen      8.0   
9       4.9       83990           27.0           11.0    i7 7th Gen      8.0   
10      4.5       52990          405.0           83.0    i5 7th Gen      8.0   
11      4.3       72990           56.0            9.0    i5 8th Gen      8.0   
12      4.5       94990          746.0          144.0    i7 8th Gen     16.0   
13      4.4       68990          351.0           75.0    i7 7th Gen      8.0   
14      4.6       61990          359.0           88.0    i5 7th Gen      8.0   
15      4.5       72990          712.0          120.0    i7 8th Gen      8.0   
16      4.5       90990          108.0           22.0    i7 8th Gen     16.0   
17      4.7       54990        20868.0         2411.0    i5 5th Gen      8.0   
18      NaN      189990            NaN            NaN    i7 9th Gen     16.0   
19      4.5       41990         3682.0          589.0    i5 8th Gen      8.0   
20      4.1       19990         6948.0          838.0  Dual Core A9      4.0   
21      4.6       44990         2341.0          429.0    i5 8th Gen      8.0   
22      4.3       28990         2830.0          431.0    i3 7th Gen      4.0   
23      4.6       54990          476.0           65.0    i5 9th Gen      8.0   
24      4.1       25990         3594.0          382.0    i3 7th Gen      4.0   
25      4.3       49990         1679.0          227.0    i5 8th Gen      8.0   
26      4.1       21990          753.0          155.0   3 Dual Core      4.0   
27      4.1       38990          189.0           19.0    i5 8th Gen      8.0   
28      4.4       54990          260.0           30.0    i5 8th Gen      8.0   
29      4.1       23990         2359.0          241.0    i3 7th Gen      4.0   
..      ...         ...            ...            ...           ...      ...   
782     4.4       54990          260.0           30.0    i5 8th Gen      8.0   
783     NaN      137098            NaN            NaN    i5 7th Gen      8.0   
784     4.0       52500            1.0            1.0    i5 8th Gen      8.0   
785     4.9       71890            8.0            1.0    i5 8th Gen      8.0   
786     4.5       79999          225.0           37.0    i5 7th Gen      4.0   
787     4.4       81990           19.0            4.0    i5 7th Gen      8.0   
788     4.4       29999          911.0          116.0           NaN      4.0   
789     4.2       78990           13.0            3.0    i5 8th Gen      8.0   
790     4.8      144990            4.0            1.0    i7 9th Gen     16.0   
791     4.9       67999           10.0            4.0   i5 10th Gen      8.0   
792     4.5       58244           23.0            6.0    i5 8th Gen      8.0   
793     4.2       27990         9365.0         1131.0    i3 7th Gen      4.0   
794     NaN       84990            NaN            NaN    i7 9th Gen      8.0   
795     4.8      164990           39.0            6.0    i5 8th Gen      8.0   
796     5.0       36990            6.0            1.0           NaN      4.0   
797     4.7       96499          381.0           56.0    i5 8th Gen      8.0   
798     4.0       24990         1730.0          212.0    i3 7th Gen      4.0   
799     NaN       27690            NaN            NaN    i3 7th Gen      4.0   
800  

In [49]:
columns=['Brands','Ram[GB]','Storage','Processor','Model','Rating','Disc_price','No of Ratings','No of Reviews','Operating system']
L1 = L1[columns]
L1

Brands  Ram[GB]              Storage     Processor  \
0         Acer      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
1          MSI     16.0           512 GB SSD    i7 8th Gen   
2         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
3         Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
4          MSI     16.0  1 TB HDD 512 GB SSD    i7 8th Gen   
5         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
6         Asus      8.0             1 TB HDD    i7 7th Gen   
7         Asus      8.0  1 TB HDD 256 GB SSD    i7 7th Gen   
8         Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
9          MSI      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
10        Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
11        Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
12         MSI     16.0  1 TB HDD 128 GB SSD    i7 8th Gen   
13        Asus      8.0             1 TB HDD    i7 7th Gen   
14      Lenovo      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
15         MSI      8.0  1 TB HDD 128 GB SSD    i7 8th Gen   
16        Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
17       Apple      8.0           128 GB SSD    i5 5th Gen   
18         MSI     16.0  1 TB HDD 512 GB SSD    i7 9th Gen   
19        Acer      8.0           512 GB SSD    i5 8th Gen   
20          HP      4.0             1 TB HDD  Dual Core A9   
21        Acer      8.0           512 GB SSD    i5 8th Gen   
22        Asus      4.0           256 GB SSD    i3 7th Gen   
23         MSI      8.0           512 GB SSD    i5 9th Gen   
24      Lenovo      4.0             1 TB HDD    i3 7th Gen   
25          HP      8.0             1 TB HDD    i5 8th Gen   
26        Acer      4.0             1 TB HDD   3 Dual Core   
27        Dell      8.0             1 TB HDD    i5 8th Gen   
28        Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
29        Dell      4.0             1 TB HDD    i3 7th Gen   
..         ...      ...                  ...           ...   
782       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
783         HP      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
784       Acer      8.0           256 GB SSD    i5 8th Gen   
785  Microsoft      8.0           128 GB SSD    i5 8th Gen   
786  Microsoft      4.0           128 GB SSD    i5 7th Gen   
787  Microsoft      8.0           128 GB SSD    i5 7th Gen   
788  Microsoft      4.0                  NaN           NaN   
789  Microsoft      8.0           128 GB SSD    i5 8th Gen   
790        MSI     16.0  1 TB HDD 256 GB SSD    i7 9th Gen   
791         HP      8.0           256 GB SSD   i5 10th Gen   
792     Lenovo      8.0             1 TB HDD    i5 8th Gen   
793         HP      4.0             1 TB HDD    i3 7th Gen   
794       Acer      8.0  1 TB HDD 256 GB SSD    i7 9th Gen   
795      Apple      8.0           512 GB SSD    i5 8th Gen   
796       Asus      4.0           256 GB SSD           NaN   
797      Apple      8.0           128 GB SSD    i5 8th Gen   
798       Dell      4.0             1 TB HDD    i3 7th Gen   
799       Asus      4.0             1 TB HDD    i3 7th Gen   
800       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
801     Lenovo      4.0             1 TB HDD    i3 7th Gen   
802       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
803       Asus      8.0             1 TB HDD    i5 8th Gen   
804       Dell      4.0             1 TB HDD           NaN   
805       Asus      8.0           512 GB SSD           NaN   
806       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
807         HP      8.0             1 TB HDD    i5 8th Gen   
808      Avita      8.0           256 GB SSD    i5 7th Gen   
809        MSI     16.0             1 TB SSD    i7 9th Gen   
810     Lenovo      8.0             1 TB HDD    i5 7th Gen   
811     Lenovo      4.0             1 TB HDD           NaN   

                                                 Model  Rating  Disc_price  \
0                                  Predator Helios 300     4.6       55990   
1      

In [50]:
L1

Brands  Ram[GB]              Storage     Processor  \
0         Acer      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
1          MSI     16.0           512 GB SSD    i7 8th Gen   
2         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
3         Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
4          MSI     16.0  1 TB HDD 512 GB SSD    i7 8th Gen   
5         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
6         Asus      8.0             1 TB HDD    i7 7th Gen   
7         Asus      8.0  1 TB HDD 256 GB SSD    i7 7th Gen   
8         Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
9          MSI      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
10        Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
11        Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
12         MSI     16.0  1 TB HDD 128 GB SSD    i7 8th Gen   
13        Asus      8.0             1 TB HDD    i7 7th Gen   
14      Lenovo      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
15         MSI      8.0  1 TB HDD 128 GB SSD    i7 8th Gen   
16        Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
17       Apple      8.0           128 GB SSD    i5 5th Gen   
18         MSI     16.0  1 TB HDD 512 GB SSD    i7 9th Gen   
19        Acer      8.0           512 GB SSD    i5 8th Gen   
20          HP      4.0             1 TB HDD  Dual Core A9   
21        Acer      8.0           512 GB SSD    i5 8th Gen   
22        Asus      4.0           256 GB SSD    i3 7th Gen   
23         MSI      8.0           512 GB SSD    i5 9th Gen   
24      Lenovo      4.0             1 TB HDD    i3 7th Gen   
25          HP      8.0             1 TB HDD    i5 8th Gen   
26        Acer      4.0             1 TB HDD   3 Dual Core   
27        Dell      8.0             1 TB HDD    i5 8th Gen   
28        Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
29        Dell      4.0             1 TB HDD    i3 7th Gen   
..         ...      ...                  ...           ...   
782       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
783         HP      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
784       Acer      8.0           256 GB SSD    i5 8th Gen   
785  Microsoft      8.0           128 GB SSD    i5 8th Gen   
786  Microsoft      4.0           128 GB SSD    i5 7th Gen   
787  Microsoft      8.0           128 GB SSD    i5 7th Gen   
788  Microsoft      4.0                  NaN           NaN   
789  Microsoft      8.0           128 GB SSD    i5 8th Gen   
790        MSI     16.0  1 TB HDD 256 GB SSD    i7 9th Gen   
791         HP      8.0           256 GB SSD   i5 10th Gen   
792     Lenovo      8.0             1 TB HDD    i5 8th Gen   
793         HP      4.0             1 TB HDD    i3 7th Gen   
794       Acer      8.0  1 TB HDD 256 GB SSD    i7 9th Gen   
795      Apple      8.0           512 GB SSD    i5 8th Gen   
796       Asus      4.0           256 GB SSD           NaN   
797      Apple      8.0           128 GB SSD    i5 8th Gen   
798       Dell      4.0             1 TB HDD    i3 7th Gen   
799       Asus      4.0             1 TB HDD    i3 7th Gen   
800       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
801     Lenovo      4.0             1 TB HDD    i3 7th Gen   
802       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
803       Asus      8.0             1 TB HDD    i5 8th Gen   
804       Dell      4.0             1 TB HDD           NaN   
805       Asus      8.0           512 GB SSD           NaN   
806       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
807         HP      8.0             1 TB HDD    i5 8th Gen   
808      Avita      8.0           256 GB SSD    i5 7th Gen   
809        MSI     16.0             1 TB SSD    i7 9th Gen   
810     Lenovo      8.0             1 TB HDD    i5 7th Gen   
811     Lenovo      4.0             1 TB HDD           NaN   

                                                 Model  Rating  Disc_price  \
0                                  Predator Helios 300     4.6       55990   
1      

- In the Laptops data, the columns have been repositioned.

In [51]:
L1.sort_values(by='Rating',ascending=True)

Brands  Ram[GB]                  Storage             Processor  \
314     Lenovo      8.0               256 GB SSD            i7 7th Gen   
277       Dell      8.0                 1 TB HDD            i5 5th Gen   
464      Apple      4.0                      NaN            i5 5th Gen   
580       Asus      4.0               500 GB HDD      i7 Processor4 GB   
289         HP      8.0                 1 TB HDD            i5 7th Gen   
394         HP      4.0               500 GB HDD                   NaN   
759       Acer      8.0                 1 TB HDD            i5 8th Gen   
414       Dell      4.0                 1 TB HDD            i5 5th Gen   
511         HP      4.0                 1 TB HDD            i5 5th Gen   
616       Asus      4.0               500 GB HDD            i5 4th Gen   
764       Asus      4.0               256 GB SSD          Dual Core E2   
736     Lenovo      4.0               128 GB SSD                   NaN   
7         Asus      8.0      1 TB HDD 256 GB SSD            i7 7th Gen   
350     Lenovo      2.0               500 GB HDD         Dual Core 4th   
479       Asus      8.0               256 GB SSD            i5 8th Gen   
611       Asus      8.0                 1 TB HDD            i7 4th Gen   
121       Acer      4.0                      NaN                   NaN   
775      Apple     16.0               512 GB SSD     i7 Processor16 GB   
367     Lenovo      4.0                 1 TB HDD            i5 7th Gen   
741       Acer      4.0                 1 TB HDD            i3 6th Gen   
769         HP      4.0                 1 TB HDD            i3 7th Gen   
376       Dell      8.0                 1 TB HDD            i7 6th Gen   
581       Asus      2.0               500 GB HDD  Dual Core Processor2   
594       Asus      2.0               500 GB HDD         Dual Core 5th   
179     Lenovo     16.0        1 TB HDD 8 GB SSD            i7 4th Gen   
716       Asus      4.0                 1 TB HDD            i3 6th Gen   
375       Dell      8.0                 1 TB HDD            i7 6th Gen   
691         HP      4.0                 1 TB HDD            i5 8th Gen   
31        Dell      4.0                 1 TB HDD            i3 7th Gen   
521       Asus      4.0                 1 TB HDD            i3 6th Gen   
..         ...      ...                      ...                   ...   
703         HP     16.0               512 GB SSD            i7 8th Gen   
704       Dell     16.0               512 GB SSD            i7 9th Gen   
706       Dell     16.0               512 GB SSD            i7 9th Gen   
707         HP      8.0      1 TB HDD 256 GB SSD           i5 10th Gen   
711        MSI     16.0               512 GB SSD            i7 9th Gen   
719  Microsoft      8.0               256 GB SSD            i5 8th Gen   
721      Avita      8.0               128 GB SSD            i3 8th Gen   
724      Avita      8.0               128 GB SSD            i3 8th Gen   
725     Lenovo     16.0      1 TB HDD 128 GB SSD            i7 7th Gen   
727       Asus      8.0               512 GB SSD            i7 8th Gen   
733         HP      8.0  32 GB Optane 512 GB SSD           i5 10th Gen   
739      Avita      8.0               128 GB SSD            i3 8th Gen   
743      Apple      8.0               256 GB SSD                   NaN   
750       Acer      8.0    16 GB Optane 1 TB HDD            i5 8th Gen   
753       Acer      8.0               256 GB SSD            i7 7th Gen   
755         HP      8.0      1 TB HDD 256 GB SSD            i5 9th Gen   
757      Apple     16.0               512 GB SSD            i7 7th Gen   
763     Lenovo      8.0                 1 TB SSD            i3 8th Gen   
765       Asus     32.0                 1 TB SSD            i7 9th Gen   
771       Dell      8.0                 1 TB HDD            i3 8th Gen   
776       Asus      4.0                 1 TB HDD            i5 7th Gen   
777     Lenovo      4.0                 1 TB HDD            i5 6th Gen   
780        M

In [52]:
L1.sort_values(by='Rating',ascending=False)

Brands  Ram[GB]                  Storage    Processor  \
400       Acer      8.0                 2 TB HDD   i7 6th Gen   
696        MSI     16.0      1 TB HDD 512 GB SSD   i7 8th Gen   
669       Acer      8.0      2 TB HDD 256 GB SSD   i7 9th Gen   
429       Dell      4.0                 1 TB HDD   i5 6th Gen   
173        MSI     16.0      1 TB HDD 128 GB SSD   i7 7th Gen   
796       Asus      4.0               256 GB SSD          NaN   
150       Dell      8.0               256 GB SSD   i7 8th Gen   
695        MSI      8.0      1 TB HDD 128 GB SSD   i7 9th Gen   
301        MSI     16.0      1 TB HDD 128 GB SSD   i7 7th Gen   
89        Acer     16.0      1 TB HDD 256 GB SSD   i7 9th Gen   
131  Alienware     16.0      1 TB HDD 512 GB SSD   i7 6th Gen   
284        MSI     16.0      1 TB HDD 256 GB SSD   i7 7th Gen   
726     Lenovo      8.0               512 GB SSD   i5 8th Gen   
496      Apple     16.0               256 GB SSD   i7 8th Gen   
2         Asus      8.0      1 TB HDD 128 GB SSD   i7 7th Gen   
673  Microsoft      8.0               128 GB SSD   i5 8th Gen   
477       Dell      4.0                 1 TB HDD   i3 5th Gen   
456       Asus      8.0               512 GB SSD   i5 8th Gen   
791         HP      8.0               256 GB SSD  i5 10th Gen   
766         HP      8.0      1 TB HDD 256 GB SSD   i7 9th Gen   
785  Microsoft      8.0               128 GB SSD   i5 8th Gen   
9          MSI      8.0      1 TB HDD 128 GB SSD   i7 7th Gen   
541       Dell      4.0                 1 TB HDD   i3 5th Gen   
136     Lenovo      8.0                 1 TB HDD   i5 7th Gen   
517         HP     16.0      1 TB HDD 128 GB SSD   i7 7th Gen   
102         HP      8.0      1 TB HDD 256 GB SSD   i5 8th Gen   
65        Asus      8.0               512 GB SSD  i5 10th Gen   
254        MSI     16.0               512 GB SSD   i7 8th Gen   
415       Asus      8.0               512 GB SSD   i7 8th Gen   
283       Asus     16.0                 1 TB SSD   i7 9th Gen   
..         ...      ...                      ...          ...   
703         HP     16.0               512 GB SSD   i7 8th Gen   
704       Dell     16.0               512 GB SSD   i7 9th Gen   
706       Dell     16.0               512 GB SSD   i7 9th Gen   
707         HP      8.0      1 TB HDD 256 GB SSD  i5 10th Gen   
711        MSI     16.0               512 GB SSD   i7 9th Gen   
719  Microsoft      8.0               256 GB SSD   i5 8th Gen   
721      Avita      8.0               128 GB SSD   i3 8th Gen   
724      Avita      8.0               128 GB SSD   i3 8th Gen   
725     Lenovo     16.0      1 TB HDD 128 GB SSD   i7 7th Gen   
727       Asus      8.0               512 GB SSD   i7 8th Gen   
733         HP      8.0  32 GB Optane 512 GB SSD  i5 10th Gen   
739      Avita      8.0               128 GB SSD   i3 8th Gen   
743      Apple      8.0               256 GB SSD          NaN   
750       Acer      8.0    16 GB Optane 1 TB HDD   i5 8th Gen   
753       Acer      8.0               256 GB SSD   i7 7th Gen   
755         HP      8.0      1 TB HDD 256 GB SSD   i5 9th Gen   
757      Apple     16.0               512 GB SSD   i7 7th Gen   
763     Lenovo      8.0                 1 TB SSD   i3 8th Gen   
765       Asus     32.0                 1 TB SSD   i7 9th Gen   
771       Dell      8.0                 1 TB HDD   i3 8th Gen   
776       Asus      4.0                 1 TB HDD   i5 7th Gen   
777     Lenovo      4.0                 1 TB HDD   i5 6th Gen   
780        MSI     32.0        1 TB HDD 1 TB SSD   i9 9th Gen   
781     Lenovo      8.0               512 GB SSD   i5 8th Gen   
783         HP      8.0      1 TB HDD 128 GB SSD   i5 7th Gen   
794       Acer      8.0      1 TB HDD 256 GB SSD   i7 9th Gen   
799       Asus      4.0                 1 TB HDD   i3 7th Gen   
804       Dell      4.0                 1 TB HDD          NaN   
805       Asus      8.0               512 GB SSD          NaN   
809        MSI     16.0                 1 T

#### Observation:-
- The Laptops have been arranged in the order of the highest to lowest rated laptops
- In which Apple Mac book has been rated 5.0 by 12 members and 1 review was given so this is considered best laptop in Apple and by the use or product rating.
- The least rating is Lenovo and Dell in which rating was 1.0 and 1.6 given by 1 member and 1 review provided,12 members and 1 review respectively.

### Treating missing values

In [53]:
L1['Operating system'].replace(to_replace='512',value='Mac',inplace=True)
L1

C:\Users\Yamini\Anaconda3\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


Brands  Ram[GB]              Storage     Processor  \
0         Acer      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
1          MSI     16.0           512 GB SSD    i7 8th Gen   
2         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
3         Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
4          MSI     16.0  1 TB HDD 512 GB SSD    i7 8th Gen   
5         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
6         Asus      8.0             1 TB HDD    i7 7th Gen   
7         Asus      8.0  1 TB HDD 256 GB SSD    i7 7th Gen   
8         Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
9          MSI      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
10        Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
11        Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
12         MSI     16.0  1 TB HDD 128 GB SSD    i7 8th Gen   
13        Asus      8.0             1 TB HDD    i7 7th Gen   
14      Lenovo      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
15         MSI      8.0  1 TB HDD 128 GB SSD    i7 8th Gen   
16        Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
17       Apple      8.0           128 GB SSD    i5 5th Gen   
18         MSI     16.0  1 TB HDD 512 GB SSD    i7 9th Gen   
19        Acer      8.0           512 GB SSD    i5 8th Gen   
20          HP      4.0             1 TB HDD  Dual Core A9   
21        Acer      8.0           512 GB SSD    i5 8th Gen   
22        Asus      4.0           256 GB SSD    i3 7th Gen   
23         MSI      8.0           512 GB SSD    i5 9th Gen   
24      Lenovo      4.0             1 TB HDD    i3 7th Gen   
25          HP      8.0             1 TB HDD    i5 8th Gen   
26        Acer      4.0             1 TB HDD   3 Dual Core   
27        Dell      8.0             1 TB HDD    i5 8th Gen   
28        Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
29        Dell      4.0             1 TB HDD    i3 7th Gen   
..         ...      ...                  ...           ...   
782       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
783         HP      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
784       Acer      8.0           256 GB SSD    i5 8th Gen   
785  Microsoft      8.0           128 GB SSD    i5 8th Gen   
786  Microsoft      4.0           128 GB SSD    i5 7th Gen   
787  Microsoft      8.0           128 GB SSD    i5 7th Gen   
788  Microsoft      4.0                  NaN           NaN   
789  Microsoft      8.0           128 GB SSD    i5 8th Gen   
790        MSI     16.0  1 TB HDD 256 GB SSD    i7 9th Gen   
791         HP      8.0           256 GB SSD   i5 10th Gen   
792     Lenovo      8.0             1 TB HDD    i5 8th Gen   
793         HP      4.0             1 TB HDD    i3 7th Gen   
794       Acer      8.0  1 TB HDD 256 GB SSD    i7 9th Gen   
795      Apple      8.0           512 GB SSD    i5 8th Gen   
796       Asus      4.0           256 GB SSD           NaN   
797      Apple      8.0           128 GB SSD    i5 8th Gen   
798       Dell      4.0             1 TB HDD    i3 7th Gen   
799       Asus      4.0             1 TB HDD    i3 7th Gen   
800       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
801     Lenovo      4.0             1 TB HDD    i3 7th Gen   
802       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
803       Asus      8.0             1 TB HDD    i5 8th Gen   
804       Dell      4.0             1 TB HDD           NaN   
805       Asus      8.0           512 GB SSD           NaN   
806       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
807         HP      8.0             1 TB HDD    i5 8th Gen   
808      Avita      8.0           256 GB SSD    i5 7th Gen   
809        MSI     16.0             1 TB SSD    i7 9th Gen   
810     Lenovo      8.0             1 TB HDD    i5 7th Gen   
811     Lenovo      4.0             1 TB HDD           NaN   

                                                 Model  Rating  Disc_price  \
0                                  Predator Helios 300     4.6       55990   
1      

In [54]:
L1.sort_values(by='Disc_price',ascending=False)

Brands  Ram[GB]                Storage             Processor  \
780        MSI     32.0      1 TB HDD 1 TB SSD            i9 9th Gen   
210        MSI     32.0    1 TB HDD 512 GB SSD            i7 8th Gen   
683         HP     16.0               1 TB SSD            i7 8th Gen   
697       Asus     32.0               1 TB SSD            i7 9th Gen   
506         HP     16.0               2 TB SSD            i9 9th Gen   
197        MSI     32.0               1 TB SSD            i7 9th Gen   
470         HP     16.0               1 TB SSD            i7 9th Gen   
757      Apple     16.0             512 GB SSD            i7 7th Gen   
809        MSI     16.0               1 TB SSD            i7 9th Gen   
561      Apple     16.0             512 GB SSD            i7 7th Gen   
765       Asus     32.0               1 TB SSD            i7 9th Gen   
284        MSI     16.0    1 TB HDD 256 GB SSD            i7 7th Gen   
475         HP     16.0             512 GB SSD            i7 9th Gen   
536         HP     16.0             512 GB SSD            i7 8th Gen   
369      Apple     16.0  512 GB HDD 512 GB SSD            i7 5th Gen   
131  Alienware     16.0    1 TB HDD 512 GB SSD            i7 6th Gen   
696        MSI     16.0    1 TB HDD 512 GB SSD            i7 8th Gen   
254        MSI     16.0             512 GB SSD            i7 8th Gen   
496      Apple     16.0             256 GB SSD            i7 8th Gen   
18         MSI     16.0    1 TB HDD 512 GB SSD            i7 9th Gen   
686        MSI     16.0             512 GB SSD            i7 8th Gen   
154  Alienware     16.0    1 TB HDD 512 GB SSD            i7 7th Gen   
689        MSI     16.0    1 TB HDD 256 GB SSD            i7 7th Gen   
711        MSI     16.0             512 GB SSD            i7 9th Gen   
671       Acer     16.0    2 TB HDD 256 GB SSD            i7 9th Gen   
4          MSI     16.0    1 TB HDD 512 GB SSD            i7 8th Gen   
200        MSI     32.0               1 TB SSD            i7 9th Gen   
406  Alienware      8.0    1 TB HDD 256 GB SSD            i7 7th Gen   
703         HP     16.0             512 GB SSD            i7 8th Gen   
775      Apple     16.0             512 GB SSD     i7 Processor16 GB   
..         ...      ...                    ...                   ...   
105      Avita      4.0                    NaN  Dual Core Processor4   
595       Dell      4.0             500 GB HDD                   NaN   
714     Lenovo      4.0             500 GB HDD          Dual Core A6   
483         HP      4.0             500 GB HDD  Dual Core Processor4   
51        Acer      4.0             500 GB HDD                   NaN   
42          HP      4.0             256 GB SSD          Dual Core A9   
20          HP      4.0               1 TB HDD          Dual Core A9   
574       Asus      2.0             500 GB HDD                   NaN   
594       Asus      2.0             500 GB HDD         Dual Core 5th   
570       Asus      2.0             500 GB HDD                   NaN   
494       Asus      2.0             500 GB HDD  Dual Core Processor2   
764       Asus      4.0             256 GB SSD          Dual Core E2   
282     Lenovo      4.0               1 TB HDD          Dual Core E2   
133       Asus      4.0                    NaN  Dual Core Processor4   
576       Asus      2.0             500 GB HDD                   NaN   
631       Acer      2.0              32 GB HDD  Dual Core Processor2   
129       Acer      2.0             500 GB HDD  Dual Core Processor2   
420       Asus      2.0             500 GB HDD  Dual Core Processor2   
457       Asus      2.0              32 GB HDD  Dual Core Processor2   
581       Asus      2.0             500 GB HDD  Dual Core Processor2   
204       Acer      2.0             500 GB HDD         Dual Core 4th   
513       Dell      2.0                    NaN  Dual Core Processor2   
661       Acer      2.0              32 GB SSD                   NaN   
551       Asus      2.0                    NaN  

#### Observation:-
- The highest laptop cost is Rs.3,99,990 which is in the brand MSI in both processors i7 and i9.
- The least laptop cost is Rs.11450 which is Iball laptop.

In [55]:
L1['Brands'].value_counts()

HP           239
Asus         187
Dell         100
Acer          96
Lenovo        92
MSI           47
Apple         20
Avita         12
Microsoft      9
Alienware      5
Sony           2
Iball          1
Nexstgo        1
i-Life         1
Name: Brands, dtype: int64

- The laptops available for analysis in different brands have been obtained from the dataframe

In [56]:
L1[L1['Brands']=='Acer'].sort_values(by='Disc_price',ascending=False)


Brands  Ram[GB]                Storage             Processor  \
671   Acer     16.0    2 TB HDD 256 GB SSD            i7 9th Gen   
656   Acer     16.0    1 TB HDD 256 GB SSD            i7 8th Gen   
89    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
669   Acer      8.0    2 TB HDD 256 GB SSD            i7 9th Gen   
8     Acer      8.0    1 TB HDD 128 GB SSD            i5 7th Gen   
664   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
607   Acer     12.0               1 TB HDD            i7 4th Gen   
501   Acer     16.0    1 TB HDD 128 GB SSD            i5 7th Gen   
33    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
444   Acer     12.0               1 TB HDD            i7 4th Gen   
186   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
565   Acer      8.0               1 TB HDD            i5 8th Gen   
78    Acer      8.0             512 GB SSD            i5 8th Gen   
624   Acer      8.0    1 TB HDD 128 GB SSD            i7 7th Gen   
67    Acer     16.0    1 TB HDD 256 GB SSD            i5 9th Gen   
735   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
639   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
794   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
497   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
619   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
753   Acer      8.0             256 GB SSD            i7 7th Gen   
214   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
243   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
400   Acer      8.0               2 TB HDD            i7 6th Gen   
113   Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
347   Acer      8.0               1 TB HDD            i5 8th Gen   
92    Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
685   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
225   Acer     12.0               1 TB HDD            i7 8th Gen   
617   Acer      8.0  16 GB Optane 1 TB HDD            i5 8th Gen   
..     ...      ...                    ...                   ...   
271   Acer      4.0               1 TB HDD            i3 7th Gen   
370   Acer      4.0               1 TB HDD            i3 6th Gen   
677   Acer      4.0               1 TB HDD            i3 5th Gen   
316   Acer      4.0             500 GB HDD            i5 4th Gen   
334   Acer      4.0               1 TB HDD                   NaN   
196   Acer      4.0               1 TB HDD                   NaN   
309   Acer      4.0               1 TB HDD            i3 7th Gen   
330   Acer      4.0               1 TB HDD            i3 5th Gen   
379   Acer      4.0               1 TB HDD                   NaN   
741   Acer      4.0               1 TB HDD            i3 6th Gen   
465   Acer      4.0             500 GB HDD                   NaN   
451   Acer      4.0             500 GB HDD                   NaN   
184   Acer      4.0               1 TB HDD            i3 7th Gen   
401   Acer      4.0               1 TB HDD            i3 5th Gen   
466   Acer      4.0             500 GB HDD                   NaN   
233   Acer      4.0             500 GB HDD  Dual Core Processor4   
751   Acer      4.0               1 TB HDD                   NaN   
125   Acer      4.0               1 TB HDD                   NaN   
146   Acer      4.0             500 GB HDD         Dual Core 4th   
331   Acer      4.0             500 GB HDD                   NaN   
26    Acer      4.0               1 TB HDD           3 Dual Core   
450   Acer      4.0               1 TB HDD                   NaN   
377   Acer      4.0               1 TB HDD          Dual Core A4   
413   Acer      4.0               1 TB HDD                   NaN   
51    Acer      4.0             500 GB HDD                   NaN   
631   Acer      2.0              32 GB HDD  Dual Core Processor2   
129   Acer      2.0             500 GB HDD  Dual Core Proces

In [57]:
type('Storage')

str

In [58]:
L1.shape

(812, 10)

### Treating data 
#### 1.Apple Brand(OS)

In [59]:
L1[L1['Brands']=='Apple'].sort_values(by='Disc_price',ascending=False)


Brands  Ram[GB]                Storage          Processor  \
757  Apple     16.0             512 GB SSD         i7 7th Gen   
561  Apple     16.0             512 GB SSD         i7 7th Gen   
369  Apple     16.0  512 GB HDD 512 GB SSD         i7 5th Gen   
496  Apple     16.0             256 GB SSD         i7 8th Gen   
775  Apple     16.0             512 GB SSD  i7 Processor16 GB   
795  Apple      8.0             512 GB SSD         i5 8th Gen   
114  Apple      8.0             256 GB SSD         i5 8th Gen   
280  Apple      8.0             512 GB SSD         i5 7th Gen   
417  Apple      8.0             512 GB SSD         i5 5th Gen   
745  Apple      8.0             128 GB SSD         i5 8th Gen   
743  Apple      8.0             256 GB SSD                NaN   
761  Apple      8.0             128 GB SSD         i5 7th Gen   
221  Apple      8.0             256 GB SSD         i5 8th Gen   
255  Apple      8.0             256 GB SSD                NaN   
797  Apple      8.0             128 GB SSD         i5 8th Gen   
409  Apple      8.0  512 GB HDD 256 GB SSD                NaN   
464  Apple      4.0                    NaN         i5 5th Gen   
484  Apple      4.0             128 GB SSD         i5 5th Gen   
383  Apple      4.0                    NaN   i5 Processor4 GB   
17   Apple      8.0             128 GB SSD         i5 5th Gen   

                                                 Model  Rating  Disc_price  \
757                                        MacBook Pro     NaN      229990   
561                                        MacBook Pro     NaN      212449   
369                                        MacBook Pro     3.7      199900   
496                                        MacBook Pro     5.0      189990   
775                                        Macbook Pro     3.3      168299   
795                                        MacBook Pro     4.8      164990   
114                                        Macbook Pro     4.6      143990   
280                                            MacBook     NaN      128700   
417                                   MacBook Pro 2015     4.2      116690   
745                                        MacBook Pro     4.6      114990   
743                                            MacBook     NaN      112990   
761                                        MacBook Pro     4.6      112990   
221                                        MacBook Air     4.7      109990   
255                                            MacBook     NaN      104800   
797                                        MacBook Air     4.7       96499   
409                                            MacBook     4.6       93989   
464          MacBook Air 2015 MJVP2HN/A (Ultrabook ) (     2.0       79900   
484                                        MacBook Air     4.1       65900   
383  MD760HN/B MacBook Air (Ci5/ 4GB/ 128GB Flash/ ...     4.6       60693   
17                                         MacBook Air     4.7       54990   

     No of Ratings  No of Reviews Operating system  
757            NaN            NaN              Mac  
561            NaN            NaN              Mac  
369           38.0           19.0              Mac  
496           12.0            1.0              Mac  
775           78.0           40.0              Mac  
795           39.0            6.0              Mac  
114          108.0           25.0              Mac  
280            NaN            NaN              Mac  
417           27.0            6.0               OS  
745           20.0            2.0              Mac  
743            NaN            NaN              Mac  
761           98.0           12.0              Mac  
221          152.0           18.0              Mac  
255            NaN            NaN              Mac  
797          381.0           56.0              Mac  
409           12.0            2.0              256  
464           15.0            8.0              NaN  
484           48.0           10.0            

In [60]:
Apple = L1[L1['Brands']=='Apple'].sort_values(by='Disc_price',ascending=False)
Apple

Brands  Ram[GB]                Storage          Processor  \
757  Apple     16.0             512 GB SSD         i7 7th Gen   
561  Apple     16.0             512 GB SSD         i7 7th Gen   
369  Apple     16.0  512 GB HDD 512 GB SSD         i7 5th Gen   
496  Apple     16.0             256 GB SSD         i7 8th Gen   
775  Apple     16.0             512 GB SSD  i7 Processor16 GB   
795  Apple      8.0             512 GB SSD         i5 8th Gen   
114  Apple      8.0             256 GB SSD         i5 8th Gen   
280  Apple      8.0             512 GB SSD         i5 7th Gen   
417  Apple      8.0             512 GB SSD         i5 5th Gen   
745  Apple      8.0             128 GB SSD         i5 8th Gen   
743  Apple      8.0             256 GB SSD                NaN   
761  Apple      8.0             128 GB SSD         i5 7th Gen   
221  Apple      8.0             256 GB SSD         i5 8th Gen   
255  Apple      8.0             256 GB SSD                NaN   
797  Apple      8.0             128 GB SSD         i5 8th Gen   
409  Apple      8.0  512 GB HDD 256 GB SSD                NaN   
464  Apple      4.0                    NaN         i5 5th Gen   
484  Apple      4.0             128 GB SSD         i5 5th Gen   
383  Apple      4.0                    NaN   i5 Processor4 GB   
17   Apple      8.0             128 GB SSD         i5 5th Gen   

                                                 Model  Rating  Disc_price  \
757                                        MacBook Pro     NaN      229990   
561                                        MacBook Pro     NaN      212449   
369                                        MacBook Pro     3.7      199900   
496                                        MacBook Pro     5.0      189990   
775                                        Macbook Pro     3.3      168299   
795                                        MacBook Pro     4.8      164990   
114                                        Macbook Pro     4.6      143990   
280                                            MacBook     NaN      128700   
417                                   MacBook Pro 2015     4.2      116690   
745                                        MacBook Pro     4.6      114990   
743                                            MacBook     NaN      112990   
761                                        MacBook Pro     4.6      112990   
221                                        MacBook Air     4.7      109990   
255                                            MacBook     NaN      104800   
797                                        MacBook Air     4.7       96499   
409                                            MacBook     4.6       93989   
464          MacBook Air 2015 MJVP2HN/A (Ultrabook ) (     2.0       79900   
484                                        MacBook Air     4.1       65900   
383  MD760HN/B MacBook Air (Ci5/ 4GB/ 128GB Flash/ ...     4.6       60693   
17                                         MacBook Air     4.7       54990   

     No of Ratings  No of Reviews Operating system  
757            NaN            NaN              Mac  
561            NaN            NaN              Mac  
369           38.0           19.0              Mac  
496           12.0            1.0              Mac  
775           78.0           40.0              Mac  
795           39.0            6.0              Mac  
114          108.0           25.0              Mac  
280            NaN            NaN              Mac  
417           27.0            6.0               OS  
745           20.0            2.0              Mac  
743            NaN            NaN              Mac  
761           98.0           12.0              Mac  
221          152.0           18.0              Mac  
255            NaN            NaN              Mac  
797          381.0           56.0              Mac  
409           12.0            2.0              256  
464           15.0            8.0              NaN  
484           48.0           10.0            

In [61]:
Apple['Operating system'].fillna('Mac',inplace=True)

In [62]:
Apple['Operating system'].replace(to_replace='256',value='Mac',inplace=True)

In [63]:
Apple['Operating system'].replace(to_replace='OS',value='Mac',inplace=True)

In [64]:
Apple.isnull().sum()

Brands              0
Ram[GB]             0
Storage             2
Processor           3
Model               0
Rating              5
Disc_price          0
No of Ratings       5
No of Reviews       5
Operating system    0
dtype: int64

In [65]:
Apple.tail()

Brands  Ram[GB]                Storage         Processor  \
409  Apple      8.0  512 GB HDD 256 GB SSD               NaN   
464  Apple      4.0                    NaN        i5 5th Gen   
484  Apple      4.0             128 GB SSD        i5 5th Gen   
383  Apple      4.0                    NaN  i5 Processor4 GB   
17   Apple      8.0             128 GB SSD        i5 5th Gen   

                                                 Model  Rating  Disc_price  \
409                                            MacBook     4.6       93989   
464          MacBook Air 2015 MJVP2HN/A (Ultrabook ) (     2.0       79900   
484                                        MacBook Air     4.1       65900   
383  MD760HN/B MacBook Air (Ci5/ 4GB/ 128GB Flash/ ...     4.6       60693   
17                                         MacBook Air     4.7       54990   

     No of Ratings  No of Reviews Operating system  
409           12.0            2.0              Mac  
464           15.0            8.0              Mac  
484           48.0           10.0              Mac  
383          296.0           85.0              Mac  
17         20868.0         2411.0              Mac

In [66]:
L1[L1['Brands']=='Apple']=Apple

In [67]:
Apple

Brands  Ram[GB]                Storage          Processor  \
757  Apple     16.0             512 GB SSD         i7 7th Gen   
561  Apple     16.0             512 GB SSD         i7 7th Gen   
369  Apple     16.0  512 GB HDD 512 GB SSD         i7 5th Gen   
496  Apple     16.0             256 GB SSD         i7 8th Gen   
775  Apple     16.0             512 GB SSD  i7 Processor16 GB   
795  Apple      8.0             512 GB SSD         i5 8th Gen   
114  Apple      8.0             256 GB SSD         i5 8th Gen   
280  Apple      8.0             512 GB SSD         i5 7th Gen   
417  Apple      8.0             512 GB SSD         i5 5th Gen   
745  Apple      8.0             128 GB SSD         i5 8th Gen   
743  Apple      8.0             256 GB SSD                NaN   
761  Apple      8.0             128 GB SSD         i5 7th Gen   
221  Apple      8.0             256 GB SSD         i5 8th Gen   
255  Apple      8.0             256 GB SSD                NaN   
797  Apple      8.0             128 GB SSD         i5 8th Gen   
409  Apple      8.0  512 GB HDD 256 GB SSD                NaN   
464  Apple      4.0                    NaN         i5 5th Gen   
484  Apple      4.0             128 GB SSD         i5 5th Gen   
383  Apple      4.0                    NaN   i5 Processor4 GB   
17   Apple      8.0             128 GB SSD         i5 5th Gen   

                                                 Model  Rating  Disc_price  \
757                                        MacBook Pro     NaN      229990   
561                                        MacBook Pro     NaN      212449   
369                                        MacBook Pro     3.7      199900   
496                                        MacBook Pro     5.0      189990   
775                                        Macbook Pro     3.3      168299   
795                                        MacBook Pro     4.8      164990   
114                                        Macbook Pro     4.6      143990   
280                                            MacBook     NaN      128700   
417                                   MacBook Pro 2015     4.2      116690   
745                                        MacBook Pro     4.6      114990   
743                                            MacBook     NaN      112990   
761                                        MacBook Pro     4.6      112990   
221                                        MacBook Air     4.7      109990   
255                                            MacBook     NaN      104800   
797                                        MacBook Air     4.7       96499   
409                                            MacBook     4.6       93989   
464          MacBook Air 2015 MJVP2HN/A (Ultrabook ) (     2.0       79900   
484                                        MacBook Air     4.1       65900   
383  MD760HN/B MacBook Air (Ci5/ 4GB/ 128GB Flash/ ...     4.6       60693   
17                                         MacBook Air     4.7       54990   

     No of Ratings  No of Reviews Operating system  
757            NaN            NaN              Mac  
561            NaN            NaN              Mac  
369           38.0           19.0              Mac  
496           12.0            1.0              Mac  
775           78.0           40.0              Mac  
795           39.0            6.0              Mac  
114          108.0           25.0              Mac  
280            NaN            NaN              Mac  
417           27.0            6.0              Mac  
745           20.0            2.0              Mac  
743            NaN            NaN              Mac  
761           98.0           12.0              Mac  
221          152.0           18.0              Mac  
255            NaN            NaN              Mac  
797          381.0           56.0              Mac  
409           12.0            2.0              Mac  
464           15.0            8.0              Mac  
484           48.0           10.0            

##### Observation:-
- The missing values are treated in OS by replacing it with Mac OS as it is the only OS used in Apple
- In Apple Laptops the highest cost is Rs.2,29,990 and the least cost is Rs.20868
- The highest rated laptop is Apple Macbook Pro i7 8th Gen
- The Apple Laptops ratings are in the range of 2.0-5

### 2.Microsoft

In [68]:
Microsoft = L1[L1['Brands']=='Microsoft'].sort_values(by='Disc_price',ascending=False)
Microsoft

Brands  Ram[GB]     Storage   Processor  \
507  Microsoft      8.0  256 GB SSD  i5 8th Gen   
719  Microsoft      8.0  256 GB SSD  i5 8th Gen   
767  Microsoft      8.0  128 GB SSD  i5 7th Gen   
787  Microsoft      8.0  128 GB SSD  i5 7th Gen   
786  Microsoft      4.0  128 GB SSD  i5 7th Gen   
789  Microsoft      8.0  128 GB SSD  i5 8th Gen   
673  Microsoft      8.0  128 GB SSD  i5 8th Gen   
785  Microsoft      8.0  128 GB SSD  i5 8th Gen   
788  Microsoft      4.0         NaN         NaN   

                                                 Model  Rating  Disc_price  \
507                                   Surface Laptop 2     NaN      116990   
719                                      Surface Pro 6     NaN      107990   
767                                            Surface     4.4       81990   
787                                            Surface     4.4       81990   
786                                        Surface Pro     4.5       79999   
789                                   Surface Laptop 2     4.2       78990   
673                                      Surface Pro 6     4.9       71890   
785                                      Surface Pro 6     4.9       71890   
788  Surface Go Pentium Gold - (4 GB/64 GB EMMC Sto...     4.4       29999   

     No of Ratings  No of Reviews Operating system  
507            NaN            NaN  Windows 10 Home  
719            NaN            NaN  Windows 10 Home  
767           19.0            4.0     Windows 10 S  
787           19.0            4.0     Windows 10 S  
786          225.0           37.0   Windows 10 Pro  
789           13.0            3.0  Windows 10 Home  
673            8.0            1.0  Windows 10 Home  
785            8.0            1.0  Windows 10 Home  
788          911.0          116.0  Windows 10 Home

In [69]:
L1[L1['Brands']=='Microsoft']=Microsoft

### 3.Sony

In [70]:
Sony = L1[L1['Brands']=='Sony'].sort_values(by='Disc_price',ascending=False)
Sony

Brands  Ram[GB]     Storage         Processor  \
164   Sony      4.0  750 GB HDD        i5 3rd Gen   
156   Sony      4.0         NaN  i7 Processor4 GB   

                                                 Model  Rating  Disc_price  \
164                                                        3.7       69990   
156  VAIO SVE1413YPNB Laptop (3rd Gen Ci7/ 4GB/ 500...     3.8       65990   

     No of Ratings  No of Reviews Operating system  
164           26.0            6.0    Windows 8 Pro  
156           42.0           12.0              NaN

In [71]:
Sony['Operating system'].fillna('Windows 8 Pro',inplace=True)

In [72]:
Sony

Brands  Ram[GB]     Storage         Processor  \
164   Sony      4.0  750 GB HDD        i5 3rd Gen   
156   Sony      4.0         NaN  i7 Processor4 GB   

                                                 Model  Rating  Disc_price  \
164                                                        3.7       69990   
156  VAIO SVE1413YPNB Laptop (3rd Gen Ci7/ 4GB/ 500...     3.8       65990   

     No of Ratings  No of Reviews Operating system  
164           26.0            6.0    Windows 8 Pro  
156           42.0           12.0    Windows 8 Pro

In [73]:
L1[L1['Brands']=='Sony']=Sony

### 4.Avita

In [74]:
Avita = L1[L1['Brands']=='Avita'].sort_values(by='Disc_price',ascending=False)
Avita

Brands  Ram[GB]     Storage             Processor               Model  \
721  Avita      8.0  128 GB SSD            i3 8th Gen               Liber   
739  Avita      8.0  128 GB SSD            i3 8th Gen               Liber   
665  Avita      8.0  256 GB SSD            i5 7th Gen               Liber   
808  Avita      8.0  256 GB SSD            i5 7th Gen               Liber   
279  Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
724  Avita      8.0  128 GB SSD            i3 8th Gen               Liber   
40   Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
54   Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
63   Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
97   Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
108  Avita      8.0  256 GB SSD            i5 8th Gen               Liber   
105  Avita      4.0         NaN  Dual Core Processor4  Magus Celeron Dual   

     Rating  Disc_price  No of Ratings  No of Reviews Operating system  
721     NaN       45481            NaN            NaN  Windows 10 Home  
739     NaN       45481            NaN            NaN  Windows 10 Home  
665     4.4       42990          114.0           30.0  Windows 10 Home  
808     4.4       42990          114.0           30.0  Windows 10 Home  
279     4.5       41990          443.0          101.0  Windows 10 Home  
724     NaN       36990            NaN            NaN  Windows 10 Home  
40      4.5       34990          443.0          101.0  Windows 10 Home  
54      4.5       34990          443.0          101.0  Windows 10 Home  
63      4.5       34990          443.0          101.0  Windows 10 Home  
97      4.5       34990          443.0          101.0  Windows 10 Home  
108     4.5       34990          443.0          101.0  Windows 10 Home  
105     3.7       20490            3.0            1.0  Windows 10 Home

In [75]:
L1[L1['Brands']=='Avita']=Avita

### 5.MSI

In [76]:
MSI = L1[L1['Brands']=='MSI'].sort_values(by='Disc_price',ascending=False)
MSI

Brands  Ram[GB]              Storage    Processor  \
780    MSI     32.0    1 TB HDD 1 TB SSD   i9 9th Gen   
210    MSI     32.0  1 TB HDD 512 GB SSD   i7 8th Gen   
197    MSI     32.0             1 TB SSD   i7 9th Gen   
809    MSI     16.0             1 TB SSD   i7 9th Gen   
284    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
696    MSI     16.0  1 TB HDD 512 GB SSD   i7 8th Gen   
18     MSI     16.0  1 TB HDD 512 GB SSD   i7 9th Gen   
686    MSI     16.0           512 GB SSD   i7 8th Gen   
254    MSI     16.0           512 GB SSD   i7 8th Gen   
689    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
711    MSI     16.0           512 GB SSD   i7 9th Gen   
4      MSI     16.0  1 TB HDD 512 GB SSD   i7 8th Gen   
200    MSI     32.0             1 TB SSD   i7 9th Gen   
690    MSI     16.0  1 TB HDD 256 GB SSD   i7 8th Gen   
679    MSI     16.0           512 GB SSD   i7 8th Gen   
1      MSI     16.0           512 GB SSD   i7 8th Gen   
185    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
790    MSI     16.0  1 TB HDD 256 GB SSD   i7 9th Gen   
88     MSI     16.0             1 TB SSD  i7 10th Gen   
173    MSI     16.0  1 TB HDD 128 GB SSD   i7 7th Gen   
301    MSI     16.0  1 TB HDD 128 GB SSD   i7 7th Gen   
505    MSI     16.0  1 TB HDD 512 GB SSD   i7 9th Gen   
341    MSI      8.0                  NaN          NaN   
603    MSI     16.0             1 TB SSD  i7 10th Gen   
695    MSI      8.0  1 TB HDD 128 GB SSD   i7 9th Gen   
251    MSI      8.0  1 TB HDD 128 GB SSD   i7 8th Gen   
12     MSI     16.0  1 TB HDD 128 GB SSD   i7 8th Gen   
163    MSI     16.0             1 TB HDD   i7 7th Gen   
95     MSI      8.0           512 GB SSD  i5 10th Gen   
9      MSI      8.0  1 TB HDD 128 GB SSD   i7 7th Gen   
543    MSI      8.0           512 GB SSD   i7 8th Gen   
116    MSI      8.0  1 TB HDD 128 GB SSD   i5 8th Gen   
353    MSI      8.0             1 TB HDD   i7 8th Gen   
290    MSI      8.0             1 TB HDD   i7 7th Gen   
613    MSI      8.0           512 GB SSD  i7 10th Gen   
15     MSI      8.0  1 TB HDD 128 GB SSD   i7 8th Gen   
447    MSI      8.0             1 TB HDD   i5 7th Gen   
39     MSI      8.0           512 GB SSD   i7 9th Gen   
510    MSI      8.0             1 TB HDD   i7 7th Gen   
265    MSI      8.0  1 TB HDD 128 GB SSD   i5 8th Gen   
75     MSI      8.0             1 TB HDD   i5 8th Gen   
550    MSI      8.0           512 GB SSD   i5 8th Gen   
715    MSI      8.0           512 GB SSD   i5 8th Gen   
562    MSI      8.0           512 GB SSD   i5 9th Gen   
23     MSI      8.0           512 GB SSD   i5 9th Gen   
352    MSI      8.0           512 GB SSD   i5 9th Gen   
38     MSI      8.0             1 TB HDD   i5 9th Gen   

                                                 Model  Rating  Disc_price  \
780                                                        NaN      399990   
210                                                 GT     NaN      399990   
197                                                        NaN      258390   
809                                                        NaN      214990   
284                                                 GT     5.0      203991   
696                                             Raider     5.0      194990   
18                                                         NaN      189990   
686                                            Stealth     4.8      189990   
254                                                 GS     4.8      189990   
689                                                        4.2      185990   
711                                                        NaN      184990   
4                                                   GE     4.5      179990   
200                                        P65 Creator     NaN      179190   
690                                                        NaN      158990   
679                                                 GS     4.0      149990   
1                  

In [77]:
MSI['Operating system'].fillna('Windows 10',inplace=True)

In [78]:
MSI

Brands  Ram[GB]              Storage    Processor  \
780    MSI     32.0    1 TB HDD 1 TB SSD   i9 9th Gen   
210    MSI     32.0  1 TB HDD 512 GB SSD   i7 8th Gen   
197    MSI     32.0             1 TB SSD   i7 9th Gen   
809    MSI     16.0             1 TB SSD   i7 9th Gen   
284    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
696    MSI     16.0  1 TB HDD 512 GB SSD   i7 8th Gen   
18     MSI     16.0  1 TB HDD 512 GB SSD   i7 9th Gen   
686    MSI     16.0           512 GB SSD   i7 8th Gen   
254    MSI     16.0           512 GB SSD   i7 8th Gen   
689    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
711    MSI     16.0           512 GB SSD   i7 9th Gen   
4      MSI     16.0  1 TB HDD 512 GB SSD   i7 8th Gen   
200    MSI     32.0             1 TB SSD   i7 9th Gen   
690    MSI     16.0  1 TB HDD 256 GB SSD   i7 8th Gen   
679    MSI     16.0           512 GB SSD   i7 8th Gen   
1      MSI     16.0           512 GB SSD   i7 8th Gen   
185    MSI     16.0  1 TB HDD 256 GB SSD   i7 7th Gen   
790    MSI     16.0  1 TB HDD 256 GB SSD   i7 9th Gen   
88     MSI     16.0             1 TB SSD  i7 10th Gen   
173    MSI     16.0  1 TB HDD 128 GB SSD   i7 7th Gen   
301    MSI     16.0  1 TB HDD 128 GB SSD   i7 7th Gen   
505    MSI     16.0  1 TB HDD 512 GB SSD   i7 9th Gen   
341    MSI      8.0                  NaN          NaN   
603    MSI     16.0             1 TB SSD  i7 10th Gen   
695    MSI      8.0  1 TB HDD 128 GB SSD   i7 9th Gen   
251    MSI      8.0  1 TB HDD 128 GB SSD   i7 8th Gen   
12     MSI     16.0  1 TB HDD 128 GB SSD   i7 8th Gen   
163    MSI     16.0             1 TB HDD   i7 7th Gen   
95     MSI      8.0           512 GB SSD  i5 10th Gen   
9      MSI      8.0  1 TB HDD 128 GB SSD   i7 7th Gen   
543    MSI      8.0           512 GB SSD   i7 8th Gen   
116    MSI      8.0  1 TB HDD 128 GB SSD   i5 8th Gen   
353    MSI      8.0             1 TB HDD   i7 8th Gen   
290    MSI      8.0             1 TB HDD   i7 7th Gen   
613    MSI      8.0           512 GB SSD  i7 10th Gen   
15     MSI      8.0  1 TB HDD 128 GB SSD   i7 8th Gen   
447    MSI      8.0             1 TB HDD   i5 7th Gen   
39     MSI      8.0           512 GB SSD   i7 9th Gen   
510    MSI      8.0             1 TB HDD   i7 7th Gen   
265    MSI      8.0  1 TB HDD 128 GB SSD   i5 8th Gen   
75     MSI      8.0             1 TB HDD   i5 8th Gen   
550    MSI      8.0           512 GB SSD   i5 8th Gen   
715    MSI      8.0           512 GB SSD   i5 8th Gen   
562    MSI      8.0           512 GB SSD   i5 9th Gen   
23     MSI      8.0           512 GB SSD   i5 9th Gen   
352    MSI      8.0           512 GB SSD   i5 9th Gen   
38     MSI      8.0             1 TB HDD   i5 9th Gen   

                                                 Model  Rating  Disc_price  \
780                                                        NaN      399990   
210                                                 GT     NaN      399990   
197                                                        NaN      258390   
809                                                        NaN      214990   
284                                                 GT     5.0      203991   
696                                             Raider     5.0      194990   
18                                                         NaN      189990   
686                                            Stealth     4.8      189990   
254                                                 GS     4.8      189990   
689                                                        4.2      185990   
711                                                        NaN      184990   
4                                                   GE     4.5      179990   
200                                        P65 Creator     NaN      179190   
690                                                        NaN      158990   
679                                                 GS     4.0      149990   
1                  

In [79]:
L1[L1['Brands']=='MSI']=MSI

### 6.Dell

In [80]:
Dell = L1[L1['Brands']=='Dell'].sort_values(by='Disc_price',ascending=False)
Dell

Brands  Ram[GB]                Storage             Processor  \
706   Dell     16.0             512 GB SSD            i7 9th Gen   
150   Dell      8.0             256 GB SSD            i7 8th Gen   
704   Dell     16.0             512 GB SSD            i7 9th Gen   
610   Dell     16.0    1 TB HDD 256 GB SSD            i7 7th Gen   
699   Dell     16.0    1 TB HDD 256 GB SSD            i7 7th Gen   
680   Dell      8.0    1 TB HDD 512 GB SSD            i7 9th Gen   
453   Dell     16.0               2 TB HDD            i7 7th Gen   
41    Dell      8.0             256 GB SSD            i5 8th Gen   
52    Dell      8.0    1 TB HDD 512 GB SSD            i7 8th Gen   
175   Dell      8.0    2 TB HDD 128 GB SSD            i7 8th Gen   
223   Dell      8.0               1 TB HDD            i7 7th Gen   
474   Dell      8.0               1 TB HDD            i7 7th Gen   
407   Dell      8.0               1 TB HDD            i5 7th Gen   
277   Dell      8.0               1 TB HDD            i5 5th Gen   
546   Dell      8.0               2 TB HDD            i7 8th Gen   
177   Dell      8.0               1 TB HDD            i7 6th Gen   
375   Dell      8.0               1 TB HDD            i7 6th Gen   
374   Dell      8.0               1 TB HDD            i7 6th Gen   
526   Dell      8.0               1 TB HDD            i5 7th Gen   
771   Dell      8.0               1 TB HDD            i3 8th Gen   
77    Dell      8.0             512 GB SSD            i5 8th Gen   
376   Dell      8.0               1 TB HDD            i7 6th Gen   
414   Dell      4.0               1 TB HDD            i5 5th Gen   
422   Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
448   Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
28    Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
398   Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
592   Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
490   Dell      4.0  16 GB Optane 2 TB HDD            i5 8th Gen   
542   Dell      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
..     ...      ...                    ...                   ...   
385   Dell      4.0               1 TB HDD            i3 6th Gen   
476   Dell      4.0               1 TB HDD            i3 6th Gen   
749   Dell      4.0             500 GB HDD            i3 7th Gen   
124   Dell      4.0                    NaN                   NaN   
461   Dell      4.0             500 GB HDD         Dual Core 4th   
713   Dell      4.0               1 TB HDD            i3 7th Gen   
591   Dell      4.0             500 GB HDD            i3 4th Gen   
623   Dell      4.0               1 TB HDD            i3 5th Gen   
597   Dell      4.0                    NaN                   NaN   
165   Dell      4.0             500 GB HDD            i3 4th Gen   
730   Dell      4.0             500 GB HDD            i3 4th Gen   
495   Dell      4.0               1 TB HDD            i3 6th Gen   
575   Dell      4.0             500 GB HDD            i3 4th Gen   
31    Dell      4.0               1 TB HDD            i3 7th Gen   
343   Dell      4.0               1 TB HDD            i3 5th Gen   
395   Dell      4.0             500 GB HDD            i3 4th Gen   
625   Dell      4.0             500 GB HDD                   NaN   
481   Dell      4.0               1 TB HDD            i3 6th Gen   
573   Dell      4.0                    NaN          Dual Core E1   
155   Dell      4.0             500 GB HDD         Dual Core 5th   
363   Dell      4.0             500 GB HDD                   NaN   
798   Dell      4.0               1 TB HDD            i3 7th Gen   
29    Dell      4.0               1 TB HDD            i3 7th Gen   
629   Dell      4.0               1 TB HDD                   NaN   
593   Dell      4.0             500 GB HDD          Dual Core E2   
127   Dell      4.0             500 GB HDD         Dual Core 5th   
115   Dell      4.0             500 GB HDD  Dual Core Proces

In [81]:
Dell['Operating system'].fillna('Windows 10 Home',inplace=True)

In [82]:
Dell.isnull().sum()

Brands               0
Ram[GB]              0
Storage              6
Processor           13
Model                0
Rating               9
Disc_price           0
No of Ratings        9
No of Reviews        9
Operating system     0
dtype: int64

In [83]:
L1[L1['Brands']=='Dell']=Dell

### 7.HP(Hewlett Packard)

In [84]:
HP = L1[L1['Brands']=='HP'].sort_values(by='Disc_price',ascending=False)
HP

Brands  Ram[GB]                  Storage             Processor  \
683     HP     16.0                 1 TB SSD            i7 8th Gen   
506     HP     16.0                 2 TB SSD            i9 9th Gen   
470     HP     16.0                 1 TB SSD            i7 9th Gen   
475     HP     16.0               512 GB SSD            i7 9th Gen   
536     HP     16.0               512 GB SSD            i7 8th Gen   
703     HP     16.0               512 GB SSD            i7 8th Gen   
529     HP     16.0      1 TB HDD 256 GB SSD            i7 8th Gen   
445     HP     16.0      1 TB HDD 512 GB SSD            i7 9th Gen   
209     HP     16.0      1 TB HDD 128 GB SSD            i7 7th Gen   
455     HP     16.0      1 TB HDD 128 GB SSD            i7 7th Gen   
493     HP      8.0               512 GB SSD            i7 6th Gen   
783     HP      8.0      1 TB HDD 128 GB SSD            i5 7th Gen   
517     HP     16.0      1 TB HDD 128 GB SSD            i7 7th Gen   
556     HP      8.0               256 GB SSD                   NaN   
486     HP     16.0      1 TB HDD 128 GB SSD            i5 7th Gen   
760     HP     12.0               512 GB SSD            i7 8th Gen   
373     HP     16.0      1 TB HDD 128 GB SSD            i7 6th Gen   
647     HP     16.0  32 GB Optane 512 GB SSD           i7 10th Gen   
563     HP     12.0                 1 TB HDD            i7 6th Gen   
555     HP      8.0               512 GB SSD            i7 7th Gen   
291     HP      8.0      1 TB HDD 128 GB SSD            i7 7th Gen   
224     HP      8.0      1 TB HDD 128 GB SSD            i7 8th Gen   
351     HP      8.0               256 GB SSD            i7 8th Gen   
766     HP      8.0      1 TB HDD 256 GB SSD            i7 9th Gen   
559     HP     16.0                 2 TB HDD            i7 7th Gen   
469     HP     16.0                 2 TB HDD            i7 7th Gen   
746     HP      8.0    16 GB Optane 1 TB HDD            i7 8th Gen   
560     HP     16.0                 2 TB HDD            i7 6th Gen   
321     HP      8.0      1 TB HDD 128 GB SSD            i5 7th Gen   
773     HP      8.0        1 TB HDD 8 GB SSD            i5 8th Gen   
..     ...      ...                      ...                   ...   
545     HP      4.0                 1 TB HDD          Dual Core A9   
522     HP      4.0                 1 TB HDD            i3 7th Gen   
452     HP      4.0                 1 TB HDD            i3 7th Gen   
498     HP      4.0                 1 TB HDD            i3 7th Gen   
188     HP      4.0                 1 TB HDD            i3 7th Gen   
478     HP      4.0                 1 TB HDD            i3 7th Gen   
520     HP      4.0                 1 TB HDD            i3 6th Gen   
626     HP      4.0                 1 TB HDD                   NaN   
729     HP      4.0                 1 TB HDD          Dual Core A9   
270     HP      4.0                 1 TB HDD            i3 6th Gen   
43      HP      4.0                 1 TB HDD            i3 7th Gen   
261     HP      4.0                      NaN                   NaN   
260     HP      4.0               500 GB HDD                   NaN   
534     HP      4.0                 1 TB HDD                   NaN   
394     HP      4.0               500 GB HDD                   NaN   
667     HP      2.0                      NaN                   NaN   
365     HP      4.0               500 GB HDD                   NaN   
327     HP      4.0               500 GB HDD                   NaN   
393     HP      4.0                 1 TB HDD  Dual Core Processor4   
384     HP      4.0                 1 TB HDD  Dual Core Processor4   
274     HP      4.0                 1 TB HDD          Dual Core E2   
710     HP      4.0                 1 TB HDD                   NaN   
313     HP      4.0                 1 TB HDD          Dual Core A4   
443     HP      4.0                 1 TB HDD                   NaN   
634     HP      4.0                 1 TB HDD                   NaN   
396     HP    

In [85]:
HP['Operating system'].fillna('Windows 10 Home',inplace=True)

In [86]:
HP.isnull().sum()

Brands               0
Ram[GB]              0
Storage              6
Processor           24
Model                0
Rating              28
Disc_price           0
No of Ratings       28
No of Reviews       28
Operating system     0
dtype: int64

In [87]:
L1[L1['Brands']=='HP']=HP

### 8.Lenovo

In [88]:
Lenovo = L1[L1['Brands']=='Lenovo'].sort_values(by='Disc_price',ascending=False)
Lenovo

Brands  Ram[GB]              Storage             Processor  \
179  Lenovo     16.0    1 TB HDD 8 GB SSD            i7 4th Gen   
323  Lenovo     16.0  1 TB HDD 128 GB SSD            i7 6th Gen   
725  Lenovo     16.0  1 TB HDD 128 GB SSD            i7 7th Gen   
781  Lenovo      8.0           512 GB SSD            i5 8th Gen   
314  Lenovo      8.0           256 GB SSD            i7 7th Gen   
726  Lenovo      8.0           512 GB SSD            i5 8th Gen   
763  Lenovo      8.0             1 TB SSD            i3 8th Gen   
655  Lenovo      8.0    1 TB HDD 8 GB SSD            i7 4th Gen   
207  Lenovo      8.0           512 GB SSD            i5 8th Gen   
180  Lenovo      8.0           256 GB SSD            i5 7th Gen   
264  Lenovo      8.0  1 TB HDD 128 GB SSD            i7 9th Gen   
137  Lenovo      8.0             1 TB HDD            i7 5th Gen   
601  Lenovo      8.0             1 TB HDD            i7 5th Gen   
810  Lenovo      8.0             1 TB HDD            i5 7th Gen   
681  Lenovo      8.0             1 TB HDD            i5 8th Gen   
14   Lenovo      8.0  1 TB HDD 128 GB SSD            i5 7th Gen   
193  Lenovo      4.0             1 TB HDD            i5 7th Gen   
276  Lenovo      8.0             1 TB HDD            i7 7th Gen   
203  Lenovo      8.0             2 TB HDD            i5 7th Gen   
136  Lenovo      8.0             1 TB HDD            i5 7th Gen   
792  Lenovo      8.0             1 TB HDD            i5 8th Gen   
621  Lenovo      8.0             1 TB HDD            i5 8th Gen   
687  Lenovo      8.0             1 TB HDD            i5 7th Gen   
143  Lenovo      8.0                  NaN                   NaN   
500  Lenovo      4.0  500 GB HDD 8 GB SSD            i5 5th Gen   
615  Lenovo      4.0           500 GB HDD            i5 5th Gen   
111  Lenovo      8.0           512 GB SSD            i5 8th Gen   
367  Lenovo      4.0             1 TB HDD            i5 7th Gen   
585  Lenovo      8.0             1 TB HDD            i3 7th Gen   
82   Lenovo      8.0             1 TB HDD            i5 8th Gen   
..      ...      ...                  ...                   ...   
145  Lenovo      4.0             1 TB HDD            i3 4th Gen   
159  Lenovo      4.0           500 GB HDD                   NaN   
306  Lenovo      4.0             1 TB HDD            i3 6th Gen   
250  Lenovo      4.0             1 TB HDD            i3 6th Gen   
736  Lenovo      4.0           128 GB SSD                   NaN   
37   Lenovo      8.0             1 TB HDD                   NaN   
770  Lenovo      4.0             1 TB HDD            i3 7th Gen   
71   Lenovo      4.0             1 TB HDD            i3 7th Gen   
801  Lenovo      4.0             1 TB HDD            i3 7th Gen   
740  Lenovo      4.0             1 TB HDD            i3 4th Gen   
48   Lenovo      4.0             1 TB HDD            i3 7th Gen   
187  Lenovo      4.0           500 GB HDD            i3 6th Gen   
24   Lenovo      4.0             1 TB HDD            i3 7th Gen   
435  Lenovo      4.0             1 TB HDD            i3 5th Gen   
524  Lenovo      4.0             1 TB HDD            i3 6th Gen   
94   Lenovo      4.0             1 TB HDD            i3 7th Gen   
436  Lenovo      4.0                  NaN                   NaN   
206  Lenovo      4.0           500 GB HDD                   NaN   
811  Lenovo      4.0             1 TB HDD                   NaN   
717  Lenovo      4.0           500 GB HDD  Dual Core Processor4   
57   Lenovo      4.0             1 TB HDD            i3 7th Gen   
34   Lenovo      4.0             1 TB HDD            i3 7th Gen   
437  Lenovo      2.0           500 GB HDD                   NaN   
350  Lenovo      2.0           500 GB HDD         Dual Core 4th   
217  Lenovo      4.0           500 GB HDD                   NaN   
147  Lenovo      4.0             1 TB HDD                   NaN   
720  Lenovo      4.0             1 TB HDD          Dual Core E2   
296  Lenovo      2.0           500 GB HDD          D

In [89]:
Lenovo['Operating system'].fillna('Windows 10 Home',inplace=True)

In [90]:
Lenovo['Operating system'].isnull().sum()

0

In [91]:
Lenovo.loc[436:437]

Brands  Ram[GB]     Storage             Processor  \
436  Lenovo      4.0         NaN                   NaN   
206  Lenovo      4.0  500 GB HDD                   NaN   
811  Lenovo      4.0    1 TB HDD                   NaN   
717  Lenovo      4.0  500 GB HDD  Dual Core Processor4   
57   Lenovo      4.0    1 TB HDD            i3 7th Gen   
34   Lenovo      4.0    1 TB HDD            i3 7th Gen   
437  Lenovo      2.0  500 GB HDD                   NaN   

                         Model  Rating  Disc_price  No of Ratings  \
436  G50-45 Notebook (APU Quad     3.9       24646          142.0   
206   IdeaPad 100 Pentium Quad     3.9       23990           71.0   
811       IdeaPad Pentium Quad     4.0       23987          357.0   
717   Ideapad 330 Celeron Dual     4.1       22990          160.0   
57                 Ideapad 330     4.0       22990           61.0   
34                 Ideapad 130     4.1       22990         4248.0   
437        G50-30 Pentium Quad     3.9       22450           48.0   

     No of Reviews Operating system  
436           34.0  Windows 10 Home  
206           10.0  Windows 10 Home  
811           57.0              DOS  
717           11.0  Windows 10 Home  
57             7.0              DOS  
34           475.0              DOS  
437           11.0        Windows 8

In [92]:
L1[L1['Brands']=='Lenovo']=Lenovo

### 9. Acer

In [93]:
Acer = L1[L1['Brands']=='Acer'].sort_values(by='Disc_price',ascending=False)
Acer

Brands  Ram[GB]                Storage             Processor  \
671   Acer     16.0    2 TB HDD 256 GB SSD            i7 9th Gen   
656   Acer     16.0    1 TB HDD 256 GB SSD            i7 8th Gen   
89    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
669   Acer      8.0    2 TB HDD 256 GB SSD            i7 9th Gen   
8     Acer      8.0    1 TB HDD 128 GB SSD            i5 7th Gen   
664   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
607   Acer     12.0               1 TB HDD            i7 4th Gen   
501   Acer     16.0    1 TB HDD 128 GB SSD            i5 7th Gen   
33    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
444   Acer     12.0               1 TB HDD            i7 4th Gen   
186   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
565   Acer      8.0               1 TB HDD            i5 8th Gen   
78    Acer      8.0             512 GB SSD            i5 8th Gen   
624   Acer      8.0    1 TB HDD 128 GB SSD            i7 7th Gen   
67    Acer     16.0    1 TB HDD 256 GB SSD            i5 9th Gen   
735   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
639   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
794   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
497   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
619   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
753   Acer      8.0             256 GB SSD            i7 7th Gen   
214   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
243   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
400   Acer      8.0               2 TB HDD            i7 6th Gen   
113   Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
347   Acer      8.0               1 TB HDD            i5 8th Gen   
92    Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
685   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
225   Acer     12.0               1 TB HDD            i7 8th Gen   
617   Acer      8.0  16 GB Optane 1 TB HDD            i5 8th Gen   
..     ...      ...                    ...                   ...   
271   Acer      4.0               1 TB HDD            i3 7th Gen   
370   Acer      4.0               1 TB HDD            i3 6th Gen   
677   Acer      4.0               1 TB HDD            i3 5th Gen   
316   Acer      4.0             500 GB HDD            i5 4th Gen   
334   Acer      4.0               1 TB HDD                   NaN   
196   Acer      4.0               1 TB HDD                   NaN   
309   Acer      4.0               1 TB HDD            i3 7th Gen   
330   Acer      4.0               1 TB HDD            i3 5th Gen   
379   Acer      4.0               1 TB HDD                   NaN   
741   Acer      4.0               1 TB HDD            i3 6th Gen   
465   Acer      4.0             500 GB HDD                   NaN   
451   Acer      4.0             500 GB HDD                   NaN   
184   Acer      4.0               1 TB HDD            i3 7th Gen   
401   Acer      4.0               1 TB HDD            i3 5th Gen   
466   Acer      4.0             500 GB HDD                   NaN   
233   Acer      4.0             500 GB HDD  Dual Core Processor4   
751   Acer      4.0               1 TB HDD                   NaN   
125   Acer      4.0               1 TB HDD                   NaN   
146   Acer      4.0             500 GB HDD         Dual Core 4th   
331   Acer      4.0             500 GB HDD                   NaN   
26    Acer      4.0               1 TB HDD           3 Dual Core   
450   Acer      4.0               1 TB HDD                   NaN   
377   Acer      4.0               1 TB HDD          Dual Core A4   
413   Acer      4.0               1 TB HDD                   NaN   
51    Acer      4.0             500 GB HDD                   NaN   
631   Acer      2.0              32 GB HDD  Dual Core Processor2   
129   Acer      2.0             500 GB HDD  Dual Core Proces

In [94]:
Acer['Operating system'].fillna('Windows 10 Home',inplace = True)

In [95]:
Acer['Operating system'].isnull().sum()

0

In [96]:
Acer['Operating system'].replace(to_replace='32',value='Windows 10 Home',inplace=True)

In [97]:
Acer

Brands  Ram[GB]                Storage             Processor  \
671   Acer     16.0    2 TB HDD 256 GB SSD            i7 9th Gen   
656   Acer     16.0    1 TB HDD 256 GB SSD            i7 8th Gen   
89    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
669   Acer      8.0    2 TB HDD 256 GB SSD            i7 9th Gen   
8     Acer      8.0    1 TB HDD 128 GB SSD            i5 7th Gen   
664   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
607   Acer     12.0               1 TB HDD            i7 4th Gen   
501   Acer     16.0    1 TB HDD 128 GB SSD            i5 7th Gen   
33    Acer     16.0    1 TB HDD 256 GB SSD            i7 9th Gen   
444   Acer     12.0               1 TB HDD            i7 4th Gen   
186   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
565   Acer      8.0               1 TB HDD            i5 8th Gen   
78    Acer      8.0             512 GB SSD            i5 8th Gen   
624   Acer      8.0    1 TB HDD 128 GB SSD            i7 7th Gen   
67    Acer     16.0    1 TB HDD 256 GB SSD            i5 9th Gen   
735   Acer     16.0    1 TB HDD 128 GB SSD            i5 8th Gen   
639   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
794   Acer      8.0    1 TB HDD 256 GB SSD            i7 9th Gen   
497   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
619   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
753   Acer      8.0             256 GB SSD            i7 7th Gen   
214   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
243   Acer      8.0    1 TB HDD 128 GB SSD            i5 8th Gen   
400   Acer      8.0               2 TB HDD            i7 6th Gen   
113   Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
347   Acer      8.0               1 TB HDD            i5 8th Gen   
92    Acer      8.0    1 TB HDD 256 GB SSD            i5 9th Gen   
685   Acer      8.0    1 TB HDD 128 GB SSD            i7 8th Gen   
225   Acer     12.0               1 TB HDD            i7 8th Gen   
617   Acer      8.0  16 GB Optane 1 TB HDD            i5 8th Gen   
..     ...      ...                    ...                   ...   
271   Acer      4.0               1 TB HDD            i3 7th Gen   
370   Acer      4.0               1 TB HDD            i3 6th Gen   
677   Acer      4.0               1 TB HDD            i3 5th Gen   
316   Acer      4.0             500 GB HDD            i5 4th Gen   
334   Acer      4.0               1 TB HDD                   NaN   
196   Acer      4.0               1 TB HDD                   NaN   
309   Acer      4.0               1 TB HDD            i3 7th Gen   
330   Acer      4.0               1 TB HDD            i3 5th Gen   
379   Acer      4.0               1 TB HDD                   NaN   
741   Acer      4.0               1 TB HDD            i3 6th Gen   
465   Acer      4.0             500 GB HDD                   NaN   
451   Acer      4.0             500 GB HDD                   NaN   
184   Acer      4.0               1 TB HDD            i3 7th Gen   
401   Acer      4.0               1 TB HDD            i3 5th Gen   
466   Acer      4.0             500 GB HDD                   NaN   
233   Acer      4.0             500 GB HDD  Dual Core Processor4   
751   Acer      4.0               1 TB HDD                   NaN   
125   Acer      4.0               1 TB HDD                   NaN   
146   Acer      4.0             500 GB HDD         Dual Core 4th   
331   Acer      4.0             500 GB HDD                   NaN   
26    Acer      4.0               1 TB HDD           3 Dual Core   
450   Acer      4.0               1 TB HDD                   NaN   
377   Acer      4.0               1 TB HDD          Dual Core A4   
413   Acer      4.0               1 TB HDD                   NaN   
51    Acer      4.0             500 GB HDD                   NaN   
631   Acer      2.0              32 GB HDD  Dual Core Processor2   
129   Acer      2.0             500 GB HDD  Dual Core Proces

In [98]:
L1[L1['Brands']=='Acer'] = Acer

### 10. Asus

In [99]:
Asus = L1[L1['Brands']=='Asus'].sort_values(by='Disc_price',ascending=False)
Asus

Brands  Ram[GB]              Storage             Processor  \
697   Asus     32.0             1 TB SSD            i7 9th Gen   
765   Asus     32.0             1 TB SSD            i7 9th Gen   
779   Asus     16.0  1 TB HDD 256 GB SSD            i7 8th Gen   
533   Asus     16.0  1 TB HDD 256 GB SSD            i7 8th Gen   
283   Asus     16.0             1 TB SSD            i7 9th Gen   
509   Asus     16.0  1 TB HDD 256 GB SSD            i7 7th Gen   
7     Asus      8.0  1 TB HDD 256 GB SSD            i7 7th Gen   
694   Asus     16.0  1 TB HDD 256 GB SSD            i7 9th Gen   
540   Asus     16.0  1 TB HDD 256 GB SSD            i7 8th Gen   
6     Asus      8.0             1 TB HDD            i7 7th Gen   
489   Asus      8.0           512 GB SSD            i7 8th Gen   
586   Asus      8.0           512 GB SSD            i7 8th Gen   
630   Asus     16.0  1 TB HDD 256 GB SSD                   NaN   
449   Asus      8.0  1 TB HDD 128 GB SSD            i7 7th Gen   
460   Asus     16.0             1 TB SSD            i7 9th Gen   
566   Asus      8.0           512 GB SSD            i7 8th Gen   
5     Asus      8.0  1 TB HDD 128 GB SSD            i7 7th Gen   
16    Asus     16.0  1 TB HDD 256 GB SSD            i7 8th Gen   
456   Asus      8.0           512 GB SSD            i5 8th Gen   
65    Asus      8.0           512 GB SSD           i5 10th Gen   
246   Asus     16.0  1 TB HDD 256 GB SSD            i7 8th Gen   
2     Asus      8.0  1 TB HDD 128 GB SSD            i7 7th Gen   
637   Asus     16.0             1 TB HDD            i7 4th Gen   
55    Asus     16.0           512 GB SSD            i7 9th Gen   
800   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
645   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
515   Asus      8.0             1 TB HDD            i5 7th Gen   
701   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
64    Asus      8.0  1 TB HDD 256 GB SSD            i7 9th Gen   
693   Asus      8.0           512 GB SSD            i5 8th Gen   
..     ...      ...                  ...                   ...   
602   Asus      4.0             1 TB HDD            i3 7th Gen   
482   Asus      4.0             1 TB HDD            i3 7th Gen   
502   Asus      4.0             1 TB HDD            i3 7th Gen   
192   Asus      4.0             1 TB HDD            i3 7th Gen   
458   Asus      4.0             1 TB HDD            i3 7th Gen   
648   Asus      4.0             1 TB HDD            i3 7th Gen   
578   Asus      4.0             1 TB HDD            i3 7th Gen   
218   Asus      4.0             1 TB HDD            i3 7th Gen   
432   Asus      4.0             1 TB HDD            i3 7th Gen   
262   Asus      4.0             1 TB HDD            i3 7th Gen   
408   Asus      4.0             1 TB HDD            i3 7th Gen   
96    Asus      4.0             1 TB HDD            i3 7th Gen   
74    Asus      4.0             1 TB HDD            i3 7th Gen   
256   Asus      4.0             1 TB HDD                   NaN   
547   Asus      4.0             1 TB HDD                   NaN   
211   Asus      4.0             1 TB HDD                   NaN   
574   Asus      2.0           500 GB HDD                   NaN   
594   Asus      2.0           500 GB HDD         Dual Core 5th   
570   Asus      2.0           500 GB HDD                   NaN   
494   Asus      2.0           500 GB HDD  Dual Core Processor2   
764   Asus      4.0           256 GB SSD          Dual Core E2   
133   Asus      4.0                  NaN  Dual Core Processor4   
576   Asus      2.0           500 GB HDD                   NaN   
420   Asus      2.0           500 GB HDD  Dual Core Processor2   
457   Asus      2.0            32 GB HDD  Dual Core Processor2   
581   Asus      2.0           500 GB HDD  Dual Core Processor2   
551   Asus      2.0                  NaN                   NaN   
335   Asus      2.0                  NaN                   NaN   
403   Asus      2.0                  NaN    

In [100]:
Asus['Operating system'].fillna('Windows 10 Home',inplace = True)

In [101]:
Asus.isnull().sum()

Brands               0
Ram[GB]              0
Storage              8
Processor           22
Model                0
Rating              21
Disc_price           0
No of Ratings       21
No of Reviews       21
Operating system     0
dtype: int64

In [102]:
Asus['Operating system'].replace(to_replace='128',value='Windows 10 Home',inplace=True)

In [103]:
Asus['Operating system'].replace(to_replace='Endless',value='Windows 10 Home',inplace=True)

In [104]:
#Asus[Asus['Operating system']=='128']
Asus.loc[434:]

Brands  Ram[GB]              Storage             Processor  \
434   Asus      8.0  1 TB HDD 128 GB SSD            i7 7th Gen   
119   Asus      8.0           512 GB SSD            i5 8th Gen   
11    Asus      8.0  1 TB HDD 128 GB SSD            i5 8th Gen   
319   Asus      8.0           256 GB SSD            i5 8th Gen   
531   Asus      8.0           512 GB SSD            i5 8th Gen   
234   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
415   Asus      8.0           512 GB SSD            i7 8th Gen   
344   Asus      8.0             1 TB HDD            i7 7th Gen   
479   Asus      8.0           256 GB SSD            i5 8th Gen   
13    Asus      8.0             1 TB HDD            i7 7th Gen   
709   Asus      8.0  1 TB HDD 128 GB SSD            i5 8th Gen   
3     Asus      8.0  1 TB HDD 128 GB SSD            i5 8th Gen   
727   Asus      8.0           512 GB SSD            i7 8th Gen   
149   Asus      8.0  1 TB HDD 128 GB SSD            i5 8th Gen   
153   Asus      8.0  1 TB HDD 256 GB SSD            i5 8th Gen   
140   Asus      8.0  1 TB HDD 256 GB SSD            i5 8th Gen   
805   Asus      8.0           512 GB SSD                   NaN   
654   Asus      8.0           512 GB SSD                   NaN   
91    Asus      8.0           512 GB SSD            i5 9th Gen   
663   Asus      8.0  1 TB HDD 256 GB SSD            i5 8th Gen   
36    Asus      8.0           512 GB SSD            i5 9th Gen   
747   Asus      8.0  1 TB HDD 256 GB SSD            i5 8th Gen   
85    Asus      8.0             1 TB HDD            i5 9th Gen   
659   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
806   Asus      8.0  1 TB HDD 256 GB SSD            i7 8th Gen   
237   Asus      4.0           512 GB SSD                   NaN   
580   Asus      4.0           500 GB HDD      i7 Processor4 GB   
734   Asus      8.0           256 GB SSD            i5 8th Gen   
611   Asus      8.0             1 TB HDD            i7 4th Gen   
676   Asus      8.0  1 TB HDD 128 GB SSD            i5 8th Gen   
..     ...      ...                  ...                   ...   
602   Asus      4.0             1 TB HDD            i3 7th Gen   
482   Asus      4.0             1 TB HDD            i3 7th Gen   
502   Asus      4.0             1 TB HDD            i3 7th Gen   
192   Asus      4.0             1 TB HDD            i3 7th Gen   
458   Asus      4.0             1 TB HDD            i3 7th Gen   
648   Asus      4.0             1 TB HDD            i3 7th Gen   
578   Asus      4.0             1 TB HDD            i3 7th Gen   
218   Asus      4.0             1 TB HDD            i3 7th Gen   
432   Asus      4.0             1 TB HDD            i3 7th Gen   
262   Asus      4.0             1 TB HDD            i3 7th Gen   
408   Asus      4.0             1 TB HDD            i3 7th Gen   
96    Asus      4.0             1 TB HDD            i3 7th Gen   
74    Asus      4.0             1 TB HDD            i3 7th Gen   
256   Asus      4.0             1 TB HDD                   NaN   
547   Asus      4.0             1 TB HDD                   NaN   
211   Asus      4.0             1 TB HDD                   NaN   
574   Asus      2.0           500 GB HDD                   NaN   
594   Asus      2.0           500 GB HDD         Dual Core 5th   
570   Asus      2.0           500 GB HDD                   NaN   
494   Asus      2.0           500 GB HDD  Dual Core Processor2   
764   Asus      4.0           256 GB SSD          Dual Core E2   
133   Asus      4.0                  NaN  Dual Core Processor4   
576   Asus      2.0           500 GB HDD                   NaN   
420   Asus      2.0           500 GB HDD  Dual Core Processor2   
457   Asus      2.0            32 GB HDD  Dual Core Processor2   
581   Asus      2.0           500 GB HDD  Dual Core Processor2   
551   Asus      2.0                  NaN                   NaN   
335   Asus      2.0                  NaN                   NaN   
403   Asus      2.0                  NaN    

In [105]:
Asus.loc[74]

Brands                         Asus
Ram[GB]                           4
Storage                    1 TB HDD
Processor                i3 7th Gen
Model                      X Series
Rating                          4.1
Disc_price                    22990
No of Ratings                  1044
No of Reviews                   123
Operating system    Windows 10 Home
Name: 74, dtype: object

In [106]:
L1[L1['Brands']=='Asus'] = Asus

In [107]:
Asus.loc[74]

Brands                         Asus
Ram[GB]                           4
Storage                    1 TB HDD
Processor                i3 7th Gen
Model                      X Series
Rating                          4.1
Disc_price                    22990
No of Ratings                  1044
No of Reviews                   123
Operating system    Windows 10 Home
Name: 74, dtype: object

In [108]:
L1.loc[74]

Brands                         Asus
Ram[GB]                           4
Storage                    1 TB HDD
Processor                i3 7th Gen
Model                      X Series
Rating                          4.1
Disc_price                    22990
No of Ratings                  1044
No of Reviews                   123
Operating system    Windows 10 Home
Name: 74, dtype: object

In [109]:
L1.isnull().sum()

Brands                0
Ram[GB]               0
Storage              32
Processor            97
Model                 0
Rating              105
Disc_price            0
No of Ratings       105
No of Reviews       105
Operating system      0
dtype: int64

In [110]:
L1.notnull().sum()

Brands              812
Ram[GB]             812
Storage             780
Processor           715
Model               812
Rating              707
Disc_price          812
No of Ratings       707
No of Reviews       707
Operating system    812
dtype: int64

In [111]:
L1[L1.isnull().sum(axis=1)>3]

Brands  Ram[GB]              Storage     Processor  \
101      HP      8.0  1 TB HDD 256 GB SSD           NaN   
117      HP      8.0  1 TB HDD 128 GB SSD           NaN   
235      HP      4.0           128 GB SSD           NaN   
255   Apple      8.0           256 GB SSD           NaN   
405  i-Life      2.0                  NaN           NaN   
544    Asus      4.0           128 GB SSD           NaN   
573    Dell      4.0                  NaN  Dual Core E1   
574    Asus      2.0           500 GB HDD           NaN   
644    Dell      4.0             1 TB HDD           NaN   
654    Asus      8.0           512 GB SSD           NaN   
743   Apple      8.0           256 GB SSD           NaN   
804    Dell      4.0             1 TB HDD           NaN   
805    Asus      8.0           512 GB SSD           NaN   

                                Model  Rating  Disc_price  No of Ratings  \
101             Pavilion Ryzen 5 Quad     NaN       55940            NaN   
117       Pavilion 15-EC Ryzen 5 Quad     NaN       59990            NaN   
235  Envy x360 AG Series Ryzen 3 Quad     NaN       79339            NaN   
255                           MacBook     NaN      104800            NaN   
405              ZED Series Atom Quad     NaN       15990            NaN   
544                                       NaN       50990            NaN   
573    Vostro 3445 Notebook (APU Dual     NaN       26400            NaN   
574             X Series Pentium Quad     NaN       19600            NaN   
644        Inspiron 3000 Ryzen 3 Quad     NaN       35247            NaN   
654           ZenBook 14 Ryzen 5 Quad     NaN       61990            NaN   
743                           MacBook     NaN      112990            NaN   
804        Inspiron 3000 Ryzen 3 Quad     NaN       35247            NaN   
805           ZenBook 14 Ryzen 5 Quad     NaN       61990            NaN   

     No of Reviews Operating system  
101            NaN  Windows 10 Home  
117            NaN  Windows 10 Home  
235            NaN  Windows 10 Home  
255            NaN              Mac  
405            NaN  Windows 10 Home  
544            NaN  Windows 10 Home  
573            NaN  Windows 10 Home  
574            NaN              DOS  
644            NaN  Windows 10 Home  
654            NaN  Windows 10 Home  
743            NaN              Mac  
804            NaN  Windows 10 Home  
805            NaN  Windows 10 Home

In [112]:
L1.drop(L1[L1.isnull().sum(axis=1)>3].index,inplace=True)

In [113]:
L1.isnull().sum()

Brands               0
Ram[GB]              0
Storage             30
Processor           85
Model                0
Rating              92
Disc_price           0
No of Ratings       92
No of Reviews       92
Operating system     0
dtype: int64

In [114]:
L1.dropna(subset=['Processor'],inplace=True)

In [115]:
L1['Rating'].fillna('0',inplace=True)

In [116]:
L1.isnull().sum()

Brands               0
Ram[GB]              0
Storage             10
Processor            0
Model                0
Rating               0
Disc_price           0
No of Ratings       92
No of Reviews       92
Operating system     0
dtype: int64

In [117]:
L1.dropna(subset=['Storage'],inplace=True)

In [118]:
L1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 704 entries, 0 to 810
Data columns (total 10 columns):
Brands              704 non-null object
Ram[GB]             704 non-null float64
Storage             704 non-null object
Processor           704 non-null object
Model               704 non-null object
Rating              704 non-null object
Disc_price          704 non-null int64
No of Ratings       612 non-null float64
No of Reviews       612 non-null float64
Operating system    704 non-null object
dtypes: float64(3), int64(1), object(6)
memory usage: 60.5+ KB


In [119]:
L1['No of Ratings'].fillna('0',inplace=True)

In [120]:
L1['No of Reviews'].fillna('0',inplace=True)

In [121]:
L1.isnull().sum()

Brands              0
Ram[GB]             0
Storage             0
Processor           0
Model               0
Rating              0
Disc_price          0
No of Ratings       0
No of Reviews       0
Operating system    0
dtype: int64

In [122]:
L1.shape

(704, 10)

In [123]:
L1

Brands  Ram[GB]              Storage     Processor  \
0         Acer      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
1          MSI     16.0           512 GB SSD    i7 8th Gen   
2         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
3         Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
4          MSI     16.0  1 TB HDD 512 GB SSD    i7 8th Gen   
5         Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
6         Asus      8.0             1 TB HDD    i7 7th Gen   
7         Asus      8.0  1 TB HDD 256 GB SSD    i7 7th Gen   
8         Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
9          MSI      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
10        Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
11        Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
12         MSI     16.0  1 TB HDD 128 GB SSD    i7 8th Gen   
13        Asus      8.0             1 TB HDD    i7 7th Gen   
14      Lenovo      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
15         MSI      8.0  1 TB HDD 128 GB SSD    i7 8th Gen   
16        Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
17       Apple      8.0           128 GB SSD    i5 5th Gen   
18         MSI     16.0  1 TB HDD 512 GB SSD    i7 9th Gen   
19        Acer      8.0           512 GB SSD    i5 8th Gen   
20          HP      4.0             1 TB HDD  Dual Core A9   
21        Acer      8.0           512 GB SSD    i5 8th Gen   
22        Asus      4.0           256 GB SSD    i3 7th Gen   
23         MSI      8.0           512 GB SSD    i5 9th Gen   
24      Lenovo      4.0             1 TB HDD    i3 7th Gen   
25          HP      8.0             1 TB HDD    i5 8th Gen   
26        Acer      4.0             1 TB HDD   3 Dual Core   
27        Dell      8.0             1 TB HDD    i5 8th Gen   
28        Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
29        Dell      4.0             1 TB HDD    i3 7th Gen   
..         ...      ...                  ...           ...   
777     Lenovo      4.0             1 TB HDD    i5 6th Gen   
778       Asus      4.0           256 GB SSD    i3 7th Gen   
779       Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
780        MSI     32.0    1 TB HDD 1 TB SSD    i9 9th Gen   
781     Lenovo      8.0           512 GB SSD    i5 8th Gen   
782       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
783         HP      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
784       Acer      8.0           256 GB SSD    i5 8th Gen   
785  Microsoft      8.0           128 GB SSD    i5 8th Gen   
786  Microsoft      4.0           128 GB SSD    i5 7th Gen   
787  Microsoft      8.0           128 GB SSD    i5 7th Gen   
789  Microsoft      8.0           128 GB SSD    i5 8th Gen   
790        MSI     16.0  1 TB HDD 256 GB SSD    i7 9th Gen   
791         HP      8.0           256 GB SSD   i5 10th Gen   
792     Lenovo      8.0             1 TB HDD    i5 8th Gen   
793         HP      4.0             1 TB HDD    i3 7th Gen   
794       Acer      8.0  1 TB HDD 256 GB SSD    i7 9th Gen   
795      Apple      8.0           512 GB SSD    i5 8th Gen   
797      Apple      8.0           128 GB SSD    i5 8th Gen   
798       Dell      4.0             1 TB HDD    i3 7th Gen   
799       Asus      4.0             1 TB HDD    i3 7th Gen   
800       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
801     Lenovo      4.0             1 TB HDD    i3 7th Gen   
802       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
803       Asus      8.0             1 TB HDD    i5 8th Gen   
806       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
807         HP      8.0             1 TB HDD    i5 8th Gen   
808      Avita      8.0           256 GB SSD    i5 7th Gen   
809        MSI     16.0             1 TB SSD    i7 9th Gen   
810     Lenovo      8.0             1 TB HDD    i5 7th Gen   

                     Model Rating  Disc_price No of Ratings No of Reviews  \
0      Predator Helios 300    4.6       55990         11530          1566   
1        

In [124]:
L1.reset_index(inplace=True)

In [125]:
L1

index     Brands  Ram[GB]              Storage     Processor  \
0        0       Acer      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
1        1        MSI     16.0           512 GB SSD    i7 8th Gen   
2        2       Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
3        3       Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
4        4        MSI     16.0  1 TB HDD 512 GB SSD    i7 8th Gen   
5        5       Asus      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
6        6       Asus      8.0             1 TB HDD    i7 7th Gen   
7        7       Asus      8.0  1 TB HDD 256 GB SSD    i7 7th Gen   
8        8       Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
9        9        MSI      8.0  1 TB HDD 128 GB SSD    i7 7th Gen   
10      10       Acer      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
11      11       Asus      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
12      12        MSI     16.0  1 TB HDD 128 GB SSD    i7 8th Gen   
13      13       Asus      8.0             1 TB HDD    i7 7th Gen   
14      14     Lenovo      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
15      15        MSI      8.0  1 TB HDD 128 GB SSD    i7 8th Gen   
16      16       Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
17      17      Apple      8.0           128 GB SSD    i5 5th Gen   
18      18        MSI     16.0  1 TB HDD 512 GB SSD    i7 9th Gen   
19      19       Acer      8.0           512 GB SSD    i5 8th Gen   
20      20         HP      4.0             1 TB HDD  Dual Core A9   
21      21       Acer      8.0           512 GB SSD    i5 8th Gen   
22      22       Asus      4.0           256 GB SSD    i3 7th Gen   
23      23        MSI      8.0           512 GB SSD    i5 9th Gen   
24      24     Lenovo      4.0             1 TB HDD    i3 7th Gen   
25      25         HP      8.0             1 TB HDD    i5 8th Gen   
26      26       Acer      4.0             1 TB HDD   3 Dual Core   
27      27       Dell      8.0             1 TB HDD    i5 8th Gen   
28      28       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
29      29       Dell      4.0             1 TB HDD    i3 7th Gen   
..     ...        ...      ...                  ...           ...   
674    777     Lenovo      4.0             1 TB HDD    i5 6th Gen   
675    778       Asus      4.0           256 GB SSD    i3 7th Gen   
676    779       Asus     16.0  1 TB HDD 256 GB SSD    i7 8th Gen   
677    780        MSI     32.0    1 TB HDD 1 TB SSD    i9 9th Gen   
678    781     Lenovo      8.0           512 GB SSD    i5 8th Gen   
679    782       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
680    783         HP      8.0  1 TB HDD 128 GB SSD    i5 7th Gen   
681    784       Acer      8.0           256 GB SSD    i5 8th Gen   
682    785  Microsoft      8.0           128 GB SSD    i5 8th Gen   
683    786  Microsoft      4.0           128 GB SSD    i5 7th Gen   
684    787  Microsoft      8.0           128 GB SSD    i5 7th Gen   
685    789  Microsoft      8.0           128 GB SSD    i5 8th Gen   
686    790        MSI     16.0  1 TB HDD 256 GB SSD    i7 9th Gen   
687    791         HP      8.0           256 GB SSD   i5 10th Gen   
688    792     Lenovo      8.0             1 TB HDD    i5 8th Gen   
689    793         HP      4.0             1 TB HDD    i3 7th Gen   
690    794       Acer      8.0  1 TB HDD 256 GB SSD    i7 9th Gen   
691    795      Apple      8.0           512 GB SSD    i5 8th Gen   
692    797      Apple      8.0           128 GB SSD    i5 8th Gen   
693    798       Dell      4.0             1 TB HDD    i3 7th Gen   
694    799       Asus      4.0             1 TB HDD    i3 7th Gen   
695    800       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
696    801     Lenovo      4.0             1 TB HDD    i3 7th Gen   
697    802       Dell      8.0  1 TB HDD 128 GB SSD    i5 8th Gen   
698    803       Asus      8.0             1 TB HDD    i5 8th Gen   
699    806       Asus      8.0  1 TB HDD 256 GB SSD    i7 8th Gen   
700

In [126]:
L1.drop(columns='index',inplace=True)

In [127]:
L1.to_csv('Cleaned data csv')